### ISSUE TITLE
Plugin Foundation

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#1]
## Description

The initial plugin foundation will use package.json to make use of `wp-scripts`, `wp-env`, preparing husky and common infrastructure commands to format codes, run tests, etc, using the [Performance Lab](https://github.com/WordPress/performance) plugin as an example.

Composer packages will be installed like `squizlabs/php_codesniffer`and `wp-coding-standards/wpcs`. Composer will require PHP to be `>=5.6` and autload classes with `psr-4`:
```
"autoload": {
    "psr-4": {
      "WordPress\\Plugin_Check\\": "includes"
    }
  }
```

## Directory structure of the plugin
```
plugin-check/
├─ includes/
├─ tests/
├─ .gitignore
├─ composer.json
├─ CONTRIBUTING.md
├─ plugin-check.php
├─ README.md
├─ readme.txt
```

## Acceptance Criteria

- The main plugin file `plugin-check.php` exists
- A `composer.json` file exists with the following
    -  `"name":" wordpress/plugin-check"`
    - `"type": "wordpress-plugin"`
    - `"license": "GPL-2.0-or-later"`
     - `"description": "WordPress Plugin Checker Plugin."`
     - `"require": { "php": ">=5.6" }`
     - PSR-4 autoloading for the `/includes` folder
- The `/includes` folder exists
- The `/tests` directory exists
- A basic `README.md`, `readme.txt`  and `CONTRIBUTING.md` files exist
- An `.editorconfig` file exists to match WP Coding Standards
- A `package.json` file exists with the following
    - `"name": "plugin-check"`
    - `"license": "GPL-2.0-or-later"`
    - `"repository": "git+https://github.com/10up/plugin-check.git"`
- An `.nvmrc` file with the node version to use on the project

**Comment by felixarntz** [comment]
@jjgrainger The ACs look good to me, just nit-picking that we probably need a few more workflow related files, such as `.editorconfig`, possibly `.nvmrc` if we later also add `package.json`, things like that. We don't necessarily have to list those one by one in the ACs, but it would be good to follow the example of https://github.com/WordPress/performance.

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

I've updated the ACs to include the items you've raised and referenced the Performance Lab plugin as an example.

**Comment by felixarntz** [comment]
Thanks @jjgrainger, LGTM!
