### ISSUE TITLE
Set up JS linting for repo

### ISSUE THREAD

**Issue by jjgrainger** [10up/plugin-check#102]
Set up JS linting via ESLint for this repository to highlight formatting issues as per WP coding standards.

**Comment by felixarntz** [comment]
@spacedmonkey Is that something you'd be interested in opening a PR for? We don't need any JS build process at this point, just setting up ESLint linting and formatting with Prettier for WP coding standards in JS (e.g. with `@wordpress/scripts`) would be the scope of this issue, and then preferably add it as a CI workflow too.

**Comment by spacedmonkey** [comment]
@felixarntz I put together a PR at #104. It is simple but works.
