### ISSUE TITLE
Setup dependabot

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#108]
### Is your enhancement related to a problem? Please describe.

Setup dependabot to ensure that dependencies are up to date. 
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by swissspidy** [comment]
Especially with the second composer file added in https://github.com/10up/plugin-check/pull/166 it would be useful to set up Dependabot to keep things easier up to date
