### ISSUE TITLE
Create unit tests trait, with helper methods. 

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#109]
### Is your enhancement related to a problem? Please describe.

From this [comment](https://github.com/10up/plugin-check/pull/100/files#r1145187911). 

Move repeated logic in unit tests out to trait so it can be re-used. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by swissspidy** [comment]
Closing as maybelater. This can be done anytime bigger changes to the test suite are needed.
