### ISSUE TITLE
Remove deprecated FILTER_SANITIZE_STRING constant

### ISSUE THREAD

**Issue by joemcgill** [10up/plugin-check#110]
### Is your enhancement related to a problem? Please describe.

There are several places in the code where we are making use of the `FILTER_SANITIZE_STRING` constant that has been deprecated in PHP 8.1. These should be replaced with `[htmlspecialchars()](https://www.php.net/manual/en/function.htmlspecialchars.php)` per the PHP docs if no other alernative is better. See: https://www.php.net/manual/en/filter.filters.sanitize.php

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felixarntz** [comment]
@joemcgill I think we should rather use `FILTER_SANITIZE_FULL_SPECIAL_CHARS`, which is the equivalent of `htmlspecialchars()` that can be used with the typical PHP filter functions `filter_input()` and `filter_var()`, so that also requires fewer changes to the code.
