### ISSUE TITLE
Improve code quality of javascript

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#113]
### Is your enhancement related to a problem? Please describe.

Refactor javascript to, 

1. Remove repeated code. 
2. Use modern javascript async / await instead of thens. 
3. Minify code. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felixarntz** [comment]
@spacedmonkey This issue is quite broad. Can you please break this down into more specific issues? At a minimum, this should be broken down into 3 issues for the 3 separate points you're outlining.

**Comment by spacedmonkey** [comment]
> @spacedmonkey This issue is quite broad. Can you please break this down into more specific issues? At a minimum, this should be broken down into 3 issues for the 3 separate points you're outlining.

I will fill this ticket out with more detail on the full code review. There isn't much JS, so this does not need to be a lots of tickets.

**Comment by swissspidy** [comment]
Closing as maybelater. This can be done anytime bigger changes to the JS side are needed. For example if we ever want to do a React rewrite or so.
