### ISSUE TITLE
Inject Admin_AJAX instance into Admin_Page class

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#118]
### Is your enhancement related to a problem? Please describe.

Inject Admin_AJAX instance into Admin_Page class as part of the constructor. This improves testability and keep it inline with other classes. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felixarntz** [comment]
@spacedmonkey If we do this, we may also want to update the tests to use a mock of the `Admin_AJAX` class in the tests for `Admin_Page`.
