### ISSUE TITLE
Make the plugin checker a WP CLI package. 

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#120]
### Is your enhancement related to a problem? Please describe.

Allow users to install the plugin checker as WP CLI [package](https://developer.wordpress.org/cli/commands/package/). This expands the reach of this plugin and may also side step the need to manually bootstrap the command in. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by swissspidy** [comment]
This is covered by #153 which has the same recommendation and more details.

Duplicate of #153
