### ISSUE TITLE
Replace fetch with wp.ajax.post

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#125]
### Is your enhancement related to a problem? Please describe.

Replace javascript fetches with `wp.ajax.post`, which is a helper javascript util to connect to admin ajax. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felixarntz** [comment]
Related: #131

**Comment by swissspidy** [comment]
Closing as maybelater, as it's not really an urgent change, just something cosmetic. It can also be done the next time we need to make bigger changes to the JS.
