### ISSUE TITLE
Add a build script to minify javascript

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#126]
### Is your enhancement related to a problem? Please describe.

Add a build script to minify javascript and transpile it to a backwards compatibility JS code for better browser support. 

the WordPress/scripts library has a build script that can / should be used here. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davidperezgar** [comment]
Could you work on this issue?

**Comment by swissspidy** [comment]
Not really urgent, we can do this when bigger changes to the JS files are planned.
