### ISSUE TITLE
Decouple available checks from rest of the check running infrastructure

### ISSUE THREAD

**Issue by felixarntz** [10up/plugin-check#127]
### Is your enhancement related to a problem? Please describe.

A few problems that can be addressed by decoupling the functionality around available checks:
* It is unclear whether checks should be referenced through their object or their slug.
* Matching checks from given slugs is "randomly" handled in `Abstract_Check_Runner` instead of a dedicated place for this.
* All checks are put together, even though we fundamentally differentiate between static and runtime checks.

Proposed solution:
* Introduce an interface `Check_Repository` with methods:
    * bitwise flags as `const` values, for now only for static and runtime check types (later this can get additional flags, e.g. for stability values to filter by):
        * `const TYPE_STATIC = 1`
        * `const TYPE_RUNTIME = 2`
        * `const TYPE_ALL = 3` (same as `TYPE_STATIC | TYPE_RUNTIME`)
    * `public function register_check( string $slug, Check $check )`: Registers a check instance under a given slug.
    * `public function get_checks( int $flags = self::TYPE_ALL, array $check_slugs = array() ) : array`: Returns an array of just check objects based on the given slugs and flags (indexed array, not a map!).
* Introduce a class `Default_Check_Repository` that implements `Check_Repository` that implements the above methods:
    * The registration method should throw an exception if a check slug is already used.
    * The registration method should throw an exception if the check class implements neither `Static_Check` or `Runtime_Check`.
    * The registration method should store `Static_Check` and `Runtime_Check` instances in separate arrays internally.
    * The get checks method should return checks based on the flags. If only static checks or only runtime checks are requested, it should take the values from the respective array, otherwise it should combine both arrays.
    * The get checks method should, if a non-empty `$check_slugs` parameter is passed, filter down the list of checks based on the flags by the check slugs passed. If any of the check slugs is not present, the method should throw an exception.
    * Examples: The method should then be callable e.g. like `get_checks( Check_Repository::TYPE_STATIC | Check_Repository::TYPE_RUNTIME )` (same as `get_checks( Check_Repository::TYPE_ALL )`), or `get_checks( Check_Repository::TYPE_STATIC )` to only get static checks.
* Create a private method `Abstract_Check_Runner::register_checks()`, which should register all checks on an instance of `Default_Check_Repository`.
* In `Abstract_Check_Runner::__construct()`, call the private `register_checks()` method so that checks are registered as soon as the runner is instantiated.
* The `Abstract_Check_Runner::get_checks_to_run()` method should be updated to use the new repositories:
    * Get the passed check slugs.
    * Call the `get_checks()` method of the `Default_Check_Repository` instance, passing the check slugs and:
        * If the requirements for running runtime checks are met, with flag `TYPE_ALL`
        * Otherwise, with flag `TYPE_STATIC`
        * This method will now throw the exception as needed, so it no longer needs to be implemented here
* Remove the `Abstract_Check_Runner::has_runtime_check()` method and inline that logic instead into `Abstract_Check_Runner::prepare()` which should now be the only place this code is needed in that class. We shouldn't have the dedicated method anymore to not encourage its use. Alternatively, we could make it `private` so that it cannot be used anywhere outside the class.
* Remove the `Checks::get_checks()` method and no longer call it in the `Checks::run_checks` method. Since validation now happens elsewhere, that method should simply trust any check instances passed. Registration of the checks now happens in the new `Abstract_Check_Runner::register_checks()` method instead of here via a filter.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

I agree with the problems you've listed but have some concerns with the solution, mainly the separation of Runtime and Static checks. This feels like it adds additional complexity when I would argue that we are only concerned about the type of checks being run based on circumstance. Most cases, users will be requesting all checks run or specific checks, not necessarily running checks based on type.

In addition, we have an issue to [introduce a stability flag](https://github.com/10up/plugin-check/issues/92) (stable, experimental, etc) which brings a new attribute to checks. With your current solution this could mean creating new Repositories for each stability level. It would also mean an additional filter for others to use, which the proposed solution creates 2 separate ways to add checks.

I agree with the idea of a Check Repository and decoupling it from some of the logic around the wider infrastructure. One of the problems I've faced when getting a list of checks is with the `Checks` class `Check_Context` dependency. Having to create the `Check_Context` using the plugin parameter, and then getting the basename, added an additional step when in some cases (like with the AJAX requests) it's not needed at that stage of the process.

I think the simplest step to resolve this issue would be to remove this dependency from the Checks class. This would make getting a list of available checks easier. This could also move the running of checks out of this class and into the `Abstract_Check_Runner`, which I think based on the name makes more sense.

We could then expand on the existing check class to with additional methods for filtering out or checking checks based on whether they're runtime or static?

Let me know your thoughts here. I have other ideas at a higher level on decoupling some of the architecture which I'll try and capture in a separate issue.

**Comment by felixarntz** [comment]
@jjgrainger Sorry for the delay in response here.

> I agree with the problems you've listed but have some concerns with the solution, mainly the separation of Runtime and Static checks. This feels like it adds additional complexity when I would argue that we are only concerned about the type of checks being run based on circumstance. Most cases, users will be requesting all checks run or specific checks, not necessarily running checks based on type.

To clarify, I'm not suggesting that we create repositories for any differentiator between checks. There are fundamentally only two types of checks, static checks and runtime checks. The code is already in a few places heavily differentiating between runtime checks and static checks in how it behaves. Having to load and retrieve all checks and then filter which ones are runtime checks (or whether any of them are runtime checks) feels backwards to me - two separate repositories (using the same code FWIW through the base class) would make this logic more efficient.

> In addition, we have an issue to  [introduce a stability flag](https://github.com/10up/plugin-check/issues/92) (stable, experimental, etc) which brings a new attribute to checks. With your current solution this could mean creating new Repositories for each stability level. It would also mean an additional filter for others to use, which the proposed solution creates 2 separate ways to add checks.

I think this may be a misunderstanding of my proposal, we would only have two repositories, for static and runtime checks. Things like the stability flags would apply to any check and could be baked into the repository base class, for example the above `get_available_check_slugs()` method could receive an additional parameter for optional stability flags. We _could_ also handle the check type (runtime vs static) as a flag there, but that would only help with filtering based on whether the environment can perform runtime checks or not. It wouldn't help though with determining whether any of the returned checks is a runtime check. That's where stability flags differ: We only need them for filtering checks, but we would never use them apart from that, which is different when it comes to runtime vs static checks which result in several other changes in the logic, e.g. calling `Universal_Runtime_Environment` etc.

> I agree with the idea of a Check Repository and decoupling it from some of the logic around the wider infrastructure. One of the problems I've faced when getting a list of checks is with the `Checks` class `Check_Context` dependency. Having to create the `Check_Context` using the plugin parameter, and then getting the basename, added an additional step when in some cases (like with the AJAX requests) it's not needed at that stage of the process.
>
> I think the simplest step to resolve this issue would be to remove this dependency from the Checks class. This would make getting a list of available checks easier. This could also move the running of checks out of this class and into the `Abstract_Check_Runner`, which I think based on the name makes more sense.

That's a great point. I've opened a separate issue #156 to remove the `$plugin_main_file` parameter from the constructor, since it's not directly related to the issue described here. We can consider removing the `Checks` class entirely, though I think that can also happen later even after transferring the repository, as the critical part of decoupling it would already be done with this issue and #156.

> We could then expand on the existing check class to with additional methods for filtering out or checking checks based on whether they're runtime or static?

Which class concretely do you mean? Also see my reply above, if we use distinct repositories for static vs runtime checks, we will never need to check that by definition, since the checks would come from different classes so we would know immediately whether any runtime check is included.

**Comment by felixarntz** [comment]
@jjgrainger Based on our discussion I have updated the issue description with the new solution. Please take a look, LMKWYT.

**Comment by jjgrainger** [comment]
Thanks @felixarntz this looks good and will start engineering on this
