### ISSUE TITLE
Make methods in abstract classes that should not be overridden `final`

### ISSUE THREAD

**Issue by felixarntz** [10up/plugin-check#129]
### Is your enhancement related to a problem? Please describe.

The plugin checker contains a number of abstract classes that contributors should override. Several of these classes contain methods with an implementation that should not be overwritten.

We should lock down those parts of the codebase so that no intentional overrides are possible. If in doubt, make the method `final`. We can always remove it later if we decide it makes sense, but not vice-versa. Similarly, we should use the strictest feasible method visibility (e.g. `private` instead of `protected` where possible).

Here is a non-comprehensive list of what I propose:
* All `Abstract_Check_Runner` methods that aren't `abstract` and that are either `public` or `protected` should be made `final`. (Note that two of the `protected` methods should be made `private` as mentioned below, and those therefore don't need `final` on them.)
* `Abstract_PHP_CodeSniffer_Check::run()` should be made `final`.
* The following classes should all be made `final`:
    * `Checks`
    * `Check_Context`
    * `Check_Result`
    * `Runtime_Environment_Setup`
    * `Admin_Page`
    * `Admin_AJAX`
    * `Plugin_Check_Command`
* The following methods should all be made `private` instead of `protected`:
    * `Checks::run_check_with_result()`
    * `Abstract_Check_Runner::get_check_slugs()`
    * `Abstract_Check_Runner::has_runtime_check()`
    * All `protected` methods in `Admin_AJAX`
    * All `protected` methods in `Plugin_Check_Command`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spacedmonkey** [comment]
I think that we should hold off doing this until the codebase is a little older. There maybe good reason to override these classes.

**Comment by felixarntz** [comment]
@spacedmonkey I don't think waiting makes sense here. What you're saying is precisely why we should make those methods `final` now: If we notice that we want to override/extend certain methods or classes, we can always change them to remove the `final`. But if we don't make them `final` and people extend them for wrong reasons, we can't make them `final` later since that would be a backward compatibility break.

We need to be explicit about what our API is, otherwise we end up with the mess that WordPress core is where you can extend anything and everything in any way, which then makes iterations so slow and challenging.

**Comment by spacedmonkey** [comment]
For the record, I don't think we should use final at all. I really dislike that core has done this. Code is designed to the extended. If you know what you are doing, then you can extend it is useful ways. I don't see the benefit of locking down at all.

**Comment by felixarntz** [comment]
@spacedmonkey I disagree with your statement "Code is designed to be extended". _Some_ code is designed to be extended, not all code. As I mentioned before, an API needs to be well defined in what its extension points are. If every single class and every single method can be extended without considering the implications of it, we end up in a place where we can never change any code because almost any change breaks backward compatibility. That's where core is today.

FWIW I agree with you that core's usage of `final` is not right. But that doesn't mean that using `final` in general is bad. The point of this is not to say "these classes and methods are forever final" - the point is rather to say "these classes and methods are final until we see a useful extension point for them".

**Comment by spacedmonkey** [comment]
After my 1:1 to with @felixarntz . 

I think we should add final part of core we feel like we do not want developers to extend. We can always make these methods not final later. I think final should be used mostly used on methods over classes. I am happy with the use of final on these terms.
