### ISSUE TITLE
Runtime checks do not run in CLI

### ISSUE THREAD

**Issue by jjgrainger** [10up/plugin-check#134]
Looking into this further I found that the [`is_plugin_active`](https://github.com/10up/plugin-check/blob/trunk/includes/Checker/Abstract_Check_Runner.php#L260) returns `true` on every call in the process except for the very last call where it returns `false`. The below is the current run order.

1. [`Abstract_Check_Runner::prepare()`](https://github.com/10up/plugin-check/blob/trunk/includes/Checker/Abstract_Check_Runner.php#L151) - Plugin is seen as active, both runtime and static checks are returned. This is called on the [`muplugins_active` action](https://github.com/10up/plugin-check/blob/trunk/includes/Utilities/Plugin_Request_Utility.php#L96-L102).
2. [Plugin_Check_Command::check()](https://github.com/10up/plugin-check/blob/trunk/includes/CLI/Plugin_Check_Command.php#L127) - Getting the checks instances to check if the runtime environment setup is needed. Plugin active, both runtime and static checks returned.
3. [Abstract_Check_Runner::run()](https://github.com/10up/plugin-check/blob/trunk/includes/Checker/Abstract_Check_Runner.php#L177) - Finally run the checks in the [Plugin_Check_Command](https://github.com/10up/plugin-check/blob/trunk/includes/CLI/Plugin_Check_Command.php#L140). Plugin is **inactive**, only the static check returned.

My current thinking is the `Runtime_Environment_Setup` is impacting this as it's run just before the `Abstract_Check_Runner::run()`. So there could be a conflict between the `Runtime_Environment_Setup` and the `Universal_Runtime_Preparation` or the ordering of the setup and preparations needs correcting (see #133)

I have been able to confirm that the runtime checks do work as expected when run and results displayed are correct. However, this was hack to get this working.

**Comment by felixarntz** [comment]
@jjgrainger Ah yes that makes sense. Since the database tables are changed, the plugin will seem as if it is inactive. We need to make sure that, if it is active in the _actual_ database tables, we also set it as active in the _fake_ database tables.
