### ISSUE TITLE
Improve the copy when a plugin is valid

### ISSUE THREAD

**Issue by jjgrainger** [10up/plugin-check#138]
When the plugin has no errors and is valid, we should look at improving the copy so that it's more obvious that the plugin is valid.  At the moment, it just says checks complete.  Maybe we add a checkmark with this plugin has passed our checks, or something along those lines. 

![image-3](https://user-images.githubusercontent.com/904708/230151402-e0c1f30f-0fba-4213-8762-8507657f57fa.png)

**Comment by spacedmonkey** [comment]
This seems like a simple fix and should be part of the release.
