### ISSUE TITLE
Improve error handling if the user clicks on the 'Check it' button without selecting a plugin

### ISSUE THREAD

**Issue by jjgrainger** [10up/plugin-check#139]
When you select the 'Check it' button without selecting a plugin in the dropdown, do you feel we should add a message in the UI?  A message does appear in the console.  See screenshot. 

![image-4](https://user-images.githubusercontent.com/904708/230151994-0e022bdf-6498-4a1f-90b7-b4bfa8016285.png)

**Comment by spacedmonkey** [comment]
Maybe disable the button until a plugin is selected...

**Comment by felixarntz** [comment]
> Maybe disable the button until a plugin is selected...

+1 to that, let's disable the button until a plugin is selected. Better to be proactive than reactive in UX.
