### ISSUE TITLE
Create CLI_Runner class

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#14]
## Description 

The CLI runner class will implement the `Abstract_Check_Runner` and its methods to use Checks class to run checks for a plugin provided. CLI command class will invoke or use the instance of the CLI Runner class to use the methods of the Checks class to run the checks.

This issue is dependant on:
- #63 

## Acceptance Criteria 
- Class `CLI_Runner` should be created and exists at `includes/Checker`
- The `CLI_Runner` class extends the `Abstract_Check_Runner`
- The class contains a `is_plugin_check()` method.
    - The `is_plugin_check()` method accepts no parameters.
    - The `is_plugin_check()` method will use the global `$_REQUEST['argv']` array, and any other relevant data, to determine if the current request is for the Plugin Checker via the CLI by:
        - Checking the `$_REQUEST['argv']` contains the `wp plugin check` command (see #30) 
    - If the above conditions are correct, the method returns `true`
    - If the above conditions do not match, the method returns `false`.
- The class contains a protected `setup_checks()` method. 
    - The `setup_checks()` method accepts no parameters.
    - The `setup_checks()` method will pass the plugin name from the `$_REQUEST['argv']` to the `Checks` constructor and assign the object to the `$checks` property.
    - The `setup_checks()` method will check the `$_REQUEST['argv']` array of slugs for the checks to run. If this does not exist all checks will be run from the `Checks` `get_checks()` method.
     - The Check instances retrieved from the `Checks` class instance `get_checks()` and assigned to the `$checks_to_run` property.
- The class contains a `run()` method.
    - The `run()` method accepts no parameters.
    - The `run()` method will call the `Checks` class `run_checks()` method passing the `$checks_to_run` property. (`$this->checks->run_checks( $this->checks_to_run )`)
    - The `run()` method will return the instance of `Check_Results` returned by the `run_checks()` method.

## Test Coverage

- Test `is_plugin_check()` returns `true` when the `$_REQUEST['argv']` array contains the expected values for a Plugin Checker CLI request.
- Test `is_plugin_check()` returns `false` when the `$_REQUEST['argv']` array does not contains the expected values for a Plugin Checker CLI request.
- The `requires_universal_preperations` returns false when no Checks passed implements the `Runtime_Check` interface
- The `requires_universal_preperations` returns true when one or more Checks passed implements the `Runtime_Check` interface
- Test `prepare()` method returns `null` when the checks to run does not contain a `Check` that implements the `Runtime_Check` interface.
- Test `prepare()` method returns a `callable` cleanup function when the checks to run contains a `Check` that implements the `Runtime_Check` interface.
- Test `run()` method returns an instance of `Check_Results`.
- Test `Check_Results` returned by `run()` contains no errors/warnings when running the test `Empty_Check`
- Test `Check_Results` returned by `run()` contains errors when running the test `Error_Check`

**Comment by felixarntz** [comment]
@jjgrainger See my feedback in https://github.com/10up/plugin-check/issues/13#issuecomment-1377800576, the ACs here will need a lot more detail. This iteration should probably wait for the ACs on #13 though, or be tackled together (since adding ACs to #13 requires thinking about how #14 and #15 will work as well).

**Comment by jjgrainger** [comment]
Thanks @felixarntz I've updated the AC's for you to review. Please review and assign back to me.

**Comment by jjgrainger** [comment]
@felixarntz I've made updates here to include the new protected `setup_checks()` method.

**Comment by felixarntz** [comment]
@jjgrainger LGTM! ✅

**Comment by felixarntz** [comment]
@jjgrainger Actually... while the ACs generally look right, please review my feedback in #15, which applies here as well. Let's discuss in #15 and once we have made a decision update both issues accordingly.

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

I've added a comment to https://github.com/10up/plugin-check/issues/15#issuecomment-1412355792 suggesting an associative array of checks where the keys are slugs that could be passed by both the CLI and AJAX requests. If you agree with this approach I can update the AC's here.
