### ISSUE TITLE
Add copy to the page to make it more user friendly

### ISSUE THREAD

**Issue by jjgrainger** [10up/plugin-check#140]
> I would like to see some copy on the page, providing context on what the plugin does. That said, if its mainly plugin developers and engineers at Automattic using it, it's probably not needed. Worth adding this as a discussion point though. 

I think adding a couple of sentences on the Admin Page to guide the user on what to do and what to expect would be enough? We don't want to provide a detailed guide and we have documentation alongside this in the future? Worth discussing.

**Comment by felixarntz** [comment]
@jjgrainger I think this is something we can handle post the repository transfer, doesn't seem critical to add this messaging before, it could be done at any point.

For now, let's focus on critical bug fixes and refactoring that would be challenging to do once it gets more exposure and contributors.

**Comment by eclarke1** [comment]
Thanks @felixarntz moving back to 'Backlog' then for post-transfer
