### ISSUE TITLE
Create AJAX_Runner class

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#15]
## Description 

The AJAX runner class will implement the `Abstract_Check_Runner` and its methods to use the Checks class to run checks for a plugin provided. The AJAX function to handle the plugin check requests will use the instance of the AJAX runner class and call the `run()` method to run the checks.

This issue is dependant on:
- #63 

## Acceptance Criteria

- Class `AJAX_Runner` should be created and exists at `includes/Checker`
- The  `AJAX_Runner` class extends the `Abstract_Check_Runner`.
- The class contains a `is_plugin_check()` method.
    - The `is_plugin_check()` method accepts no parameters.
    - The `is_plugin_check()` method will use the global `$_REQUEST` array, and any other relevant data, to determine if the current request is for the Plugin Checker via an AJAX request by:
        - Checking the `$_REQUEST['action']` matches `plugin_check_run_checks` (see #31) 
        - Checking the requested URL matches `admin-ajax.php`.
        - Checking the nonce passed is valid.
    - If the above conditions are correct, the method returns `true`
    - If the above conditions do not match, the method returns `false`.
- The class contains a protected `setup_checks()` method. 
    - The `setup_checks()` method accepts no parameters.
    - The `setup_checks()` method will pass the `$_REQUEST['plugin']` to the `Checks` constructor and assign the object to the `$checks` property.
    - The `setup_checks()` method will check the `$_REQUEST['checks']` array. As it is an AJAX request only 1 check should be passed in this array. This array contains an list of Check slugs to match with those in the `Checks` class.
        - The check slugs array is compared with the Check instances retrieved from the `Checks` class instance `get_checks()`
        - The array of `Check` objects are assigned to the `$checks_to_run` property.
- The class contains a `run()` method.
    - The `run()` method accepts no parameters.
    - The `run()` method will call the `Checks` class `run_checks()` method passing the `$checks` property. (`$this->checks->run_checks( $this->checks_to_run )`)
    - The `run()` method will return the instance of `Check_Results` returned by the `run_checks()` method.

## Test Coverage

- Test `is_plugin_check()` returns `true` when the `$_REQUEST` array contains the expected values for a Plugin Checker AJAX request.
- Test `is_plugin_check()` returns `false` when the `$_REQUEST` array does not contains the expected values for a Plugin Checker AJAX request.
- The `requires_universal_preperations` returns false when no Checks passed implements the `Runtime_Check` interface
- The `requires_universal_preperations` returns true when one or more Checks passed implements the `Runtime_Check` interface
- Test `prepare()` method returns `null` when the `$_REQUEST['checks']` array does not contain a `Check` that implements the `Runtime_Check` interface.
- Test `prepare()` method returns a `callable` cleanup function when the `$_REQUEST['checks']` array contains a `Check` that implements the `Runtime_Check` interface.
- Test `run()` method returns an instance of `Check_Results`.
- Test `Check_Results` returned by `run()` contains no errors/warnings when running the test `Empty_Check`
- Test `Check_Results` returned by `run()` contains errors when running the test `Error_Check`

**Comment by felixarntz** [comment]
@jjgrainger See my feedback in https://github.com/10up/plugin-check/issues/13#issuecomment-1377800576, the ACs here will need a lot more detail. This iteration should probably wait for the ACs on #13 though, or be tackled together (since adding ACs to #13 requires thinking about how #14 and #15 will work as well).

**Comment by jjgrainger** [comment]
Thanks @felixarntz I've updated the AC's. Please review and assign back to me.

**Comment by jjgrainger** [comment]
@felixarntz I've made updates here to include the new protected `setup_checks()` method.

**Comment by felixarntz** [comment]
@jjgrainger How would checks be specified in `$_REQUEST['checks']`? I'm asking since so far we were looking at class instances for specific checks, so in what format could a query parameter (or actually also CLI arg, see #14) reference a specific check (since that would need to be a string). Should checks maybe receive some sort of `slug` that would be used as a unique identifier?

The ACs here look good, similar to those on #14, but this part is actually a bit unclear to me, and we may need to think through that further - right now I don't understand how this would work without such a refinement.

**Comment by jjgrainger** [comment]
Thanks @felixarntz this was something I noticed too.

My thinking is we update the array of Checks we have in the Checks class to be an associative array that uses a slug for each of the checks as the key. This can be used to match the Check instances based on those slugs that are passed by the CLI and AJAX requests.

If you agree with this approach I can update the AC's here and in #14 to reflect this.

**Comment by felixarntz** [comment]
Thanks @jjgrainger, that sounds good to me.

**Comment by felixarntz** [comment]
@jjgrainger Just noting that the ACs here aren't really accurate anymore given #73, but that's probably okay. Just keep in mind to work on this following #73 eventually, it should be fairly straightforward to map the original ACs here to what it should actually be given the changes made in #73.
