### ISSUE TITLE
MU Plugin support

### ISSUE THREAD

**Issue by jjgrainger** [10up/plugin-check#154]
Raised as part of a CR here - https://github.com/10up/plugin-check/pull/143#discussion_r1168949262

There's a discussion to be had around whether the Plugin Checker should support testing MU Plugins.

There will be some challenges around supporting MU plugins as we currently rely on the `muplugins_loaded` action to run logic early in the process in order to perform runtime checks. This may require some major changes to the architecture in order to support this.

There's potentially a decision around whether MU plugins should be supported at all and if they fall out of the scope of this project?

Opening this issue as a central place to discuss this.

**Comment by swissspidy** [comment]
I don't think this is in scope for the project, so I am closing this one for now. It can be reopened if deemed otherwise.
