### ISSUE TITLE
Remove constructor parameter from `Checks` class

### ISSUE THREAD

**Issue by felixarntz** [10up/plugin-check#156]
### Is your enhancement related to a problem? Please describe.

Based on https://github.com/10up/plugin-check/issues/127#issuecomment-1499122587:
* The `$plugin_main_file` parameter should be removed from the `Checks` class constructor, since it is only used in the `run_checks()` method, which is conditionally called much later.
* The `Checks::context()` method should therefore also be removed.
* The `Checks::run_checks()` method should have its signature changed to `run_checks( Check_Context $context, array $checks )`, so that the `Check_Context` for the plugin to check only needs to be passed there.
* With that, we can also remove the `Abstract_Check_Runner::get_checks_instance()` method and underlying `Abstract_Check_Runner::$checks` property which has been confusing in terms of naming and now doesn't really serve a purpose anymore, since you can just write `new Checks()` and be done with it.
* Instead, we can add a `Abstract_Check_Runner::get_check_context()` method which returns `new Check_Context( WP_PLUGIN_DIR . '/' . $this->get_plugin_basename() )`.
* The `Abstract_Check_Runner::prepare()` method that uses the (now removed) `Checks::context()` method can then instead simply use the new `get_check_context()` method.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felixarntz** [comment]
@jjgrainger Please take a look, let me know your thoughts.

This change, together with #127, will decouple the `Checks` class further from the rest of our codebase. I think we shouldn't _yet_ go the step of removing it completely, but with both of these issues we would easily be in a position to remove the class at any point in the future if we rather want to move that logic into `Abstract_Check_Runner`.

**Comment by jjgrainger** [comment]
Thanks @felixarntz I agree with these changes and will help to make a start on the #127
