### ISSUE TITLE
Add a check for the usage of private functions. 

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#158]
### Is your enhancement related to a problem? Please describe.

See https://github.com/WordPress/WordPress-Coding-Standards/issues/723

Add a check to see if developers are using private WordPress functions. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by swissspidy** [comment]
Closing as maybelater until such a sniff exists in PHPCS. Until such a sniff exists, there's not much we can do here.

In the meantime, developers can use https://github.com/swissspidy/phpstan-no-private
