### ISSUE TITLE
Create Preparation interface

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#16]
Preparations are setup steps that should run ahead of checks. This will allow any setup work required before a check can be run to take place. Each preparation will handle the logic required to prepare the environment for the checks and return a clean up function to be run after the checks are complete. 

To provide a consistent API across the infrastructure, a Preparation interface will be created. This will define a single prepare method that any class should use to define the setup logic required.

## Acceptance Criteria
- A new `Preparation` interface exists in `includes/Checker/Preparation.php`
- The `Preparation` interface contains a single public `prepare()` method
- The `prepare()` method accepts no parameters
- An `Exception` will be thrown if the `prepare()` method fails
- The `prepare()` method returns a closure

**Comment by felixarntz** [comment]
@jjgrainger ACs LGTM, though we may want to add a point to also document that the `prepare()` method returns a closure to call for clean up.
