### ISSUE TITLE
Run PHPUnit unit tests again different versions of PHP

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#164]
### Is your enhancement related to a problem? Please describe.

Run PHPUnit unit tests again different versions of PHP. We could also consider running at against different WordPress versions as well. 

<img width="338" alt="Screenshot 2023-05-12 at 10 28 30" src="https://github.com/10up/plugin-check/assets/237508/5ae85f31-4445-4e6e-9721-253f1998459c">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spacedmonkey** [comment]
What do you think @swissspidy

**Comment by swissspidy** [comment]
Makes sense to test all of the support PHP versions for sure 👍 

Edit: not to mention the different WordPress versions
