### ISSUE TITLE
Add Dependabot config

### ISSUE THREAD

**Issue by swissspidy** [10up/plugin-check#168]
### Is your enhancement related to a problem? Please describe.

Especially with the second composer file added in #166 it would be useful to set up Dependabot to keep things easier up to date

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spacedmonkey** [comment]
How is this different from #108

**Comment by swissspidy** [comment]
It isn‘t, simply didn‘t see that one
