### ISSUE TITLE
Implement header textdomain check

### ISSUE THREAD

**Issue by eclarke1** [10up/plugin-check#177]
Implements a plugin text domain check based on the [WordPress Plugin Check headers check](https://github.com/WordPress/plugin-check/blob/trunk/checks/header.php). This check can be implemented without using any base class, just needs to implement `Static_Check`.

## Acceptance Criteria
- Class `Plugin_Header_Text_Domain_Check` should exist in `includes/Checker/Checks` folder.
- Class should implement the `Static_Check` interface.
- The check will test the contents of the plugin headers to see if the `Text Domain:` value matches the plugins slug.
    - Get the contents of the plugin main files plugin headers using the [`get_plugin_data()`](https://developer.wordpress.org/reference/functions/get_plugin_data/) core function.
    - Get the value of the `Text Domain:` header.
    - Check the text domain matches the plugins slug.
    - If not, the check should raise a warning.
 
## Test Coverage
- `run()` method raises a warning when the plugin header text domain and slug do not match.
- `run()` method raises no warnings when the text domain and slug match.

**Comment by jjgrainger** [comment]
@felixarntz @mukeshpanchal27 I've updated the AC's and this is ready for review. Thanks!

**Comment by felixarntz** [comment]
@jjgrainger ACs look good so far, just one question: Do you intend to use the WordPress core built-in functions to extract the plugin header data or manually look for the specific content in the plugin main file? This kind of consideration would be good to mention here given that the ACs are pretty much high-level implementation briefs, and this would be a noteworthy decision on how to implement it.

For example, if you use the WP core functions, then just implementing `Static_Check` is good, but if you wanted to manually search in the file, it would make sense to use the `Abstract_File_Check` base class.

Personally I think using the WP core functions makes more sense, but please include the option you would like to go with.

**Comment by jjgrainger** [comment]
Thanks @felixarntz yes, the idea was to use WP core functions to retrieve this informations, in particular [get_plugin_data()](https://developer.wordpress.org/reference/functions/get_plugin_data/).

I've updated the AC's to specify this. Assigning back to you for review.

**Comment by felixarntz** [comment]
Thanks @jjgrainger, LGTM!
