### ISSUE TITLE
Implement readme 

### ISSUE THREAD

**Issue by eclarke1** [10up/plugin-check#178]
Implement a plugin readme check based on the [WordPress Plugin Check readme check](https://github.com/WordPress/plugin-check/blob/trunk/checks/readme.php). This check can be implemented without using any base class, just needs to implement `Static_Check`.

## Acceptance Criteria
- Class `Plugin_Readme_Check` should exist in `includes/Checker/Checks` folder.
- Class should extend the `Abstract_File_Check`.
- The check will test the existence of a `readme.txt` file and it's content.
    - A warning is raised If a `readme.txt` file does not exist.
    - A warning is raised If the readme contains default text.
    - A warning is raised if a reference to the plugin license does not exist in the readme.
    - A warning is raised if the plugin stable version is missing or does not match the plugin headers.

## Test Coverage
- `run()` method raises a warning when the readme.txt file is missing.
- `run()` method raises a warning when the readme.txt file contains default text.
- `run()` method raises a warning when the readme.txt file does not include the license or version.
- `run()` method raises no warnings when the readme.txt file is valid.

**Comment by jjgrainger** [comment]
@felixarntz @mukeshpanchal27 I've updated the AC's for the ticket. This is ready for review.

**Comment by felixarntz** [comment]
@jjgrainger ACs pretty much LGTM, just one comment: Shouldn't this check also rely on `Abstract_File_Check` given that we need to look for certain things in a file (`readme.txt`)? Or if not, why would you advise against using it?

**Comment by jjgrainger** [comment]
Thanks @felixarntz you're right! I've updated this to extend the `Abstract_File_Check`. Moving this to Todo.

**Comment by swissspidy** [comment]
@felixarntz @jjgrainger What do you think about making this check more extensive? The one from the other plugin is rather simple, but there are many more things that can be checked. I actually wrote a CLI command for that last year, which should be pretty easy to port over: https://github.com/swissspidy/validate-readme-command

**Comment by felixarntz** [comment]
@swissspidy That's a great idea. I'd suggest we make that an iteration via separate issue though, since the focus at this point is simply to cover the other tool's logic.

**Comment by spacedmonkey** [comment]
This check is wrong. It is possible to just use readme.md. See https://meta.trac.wordpress.org/ticket/403 && https://johnblackbourn.com/readme-md-plugin-on-wordpress-org/

**Comment by swissspidy** [comment]
I wouldn't say it is _wrong_, but that a check for `readme.md` can be added as an enhancement.

**Comment by swissspidy** [comment]
> @swissspidy That's a great idea. I'd suggest we make that an iteration via separate issue though, since the focus at this point is simply to cover the other tool's logic.

See #198
