### ISSUE TITLE
Create I18n_Usage_Check

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#18]
## Description

Checks that WordPress internationalization functions are used properly, including using a valid textdomain that matches the plugin’s textdomain in the main file comment header. It will also include checks for each of the localization functions for typos and ensure the correct parameters are passed. This will use the existing `WordPress.WP.I18n` sniff in the [WordPress Coding Standards](https://github.com/WordPress/WordPress-Coding-Standards/).

## Acceptance Criteria

- Class `I18n_Usage_Check` should be created and exists at `includes/Checker/Checks`
- Class `I18n_Usage_Check` should extend the `Abstract_PHP_CodeSniffer_Check ` abstract class
- Class should implement the public `get_args()` and return an associative array of the required PHPCS arguments
    - `'sniffs' => 'WordPress.WP.I18n'`
    - `'standard' => 'WordPress'`

## Tests Coverage
- `get_args()` method returns the expected array of PHPCS arguments for the check
- `run()` method adds a correct message to the `$check_result` when checking an invalid file
- `run()` method does not add any message to the `$check_result` when checking a valid file

**Comment by felixarntz** [comment]
@jjgrainger The ACs here were added a while ago and are outdated. They need to be updated to reflect the way the [`Abstract_PHPCodeSniffer_Check`](https://github.com/10up/plugin-check/blob/trunk/includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php) works now.

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

I've updated the AC's to reflect the changes made to the `Abstract_PHPCodeSniffer_Check`.

**Comment by felixarntz** [comment]
@jjgrainger ACs LGTM!

**Comment by vishalkakadiya** [comment]
@jjgrainger Added a `standard` argument in the task description as we need to test the translation logic against WP coding standards. Let me know if you have any other suggestions, thank you!

CC @felixarntz

**Comment by vishalkakadiya** [comment]
@jjgrainger I have addressed your feedback and left one question for you. Thank you!
