### ISSUE TITLE
Remove possible hardcoded `plugin-check` folder path

### ISSUE THREAD

**Issue by mukeshpanchal27** [10up/plugin-check#182]
### Is your enhancement related to a problem? Please describe.

Currently, there are several files within the `plugin-check` repository where we have hardcoded references to the `plugin-check` folder path. This can cause issues when the folder name is changed or when the plugin is installed in a different directory.

To address this, we propose implementing a constant, `WP_PLUGIN_CHECK_PLUGIN_DIR_NAME`, which will dynamically retrieve the folder name using `basename( WP_PLUGIN_CHECK_PLUGIN_DIR_PATH )`. This constant can then be used throughout the code base, ensuring a flexible and reliable approach.

By updating the hardcoded references with the new constant, we will improve the maintainability and adaptability of the plugin-check codebase.

cc: @jjgrainger @felixarntz

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davidperezgar** [comment]
I've searched for hard coded and I don't see it any reference. Maybe it's an old issue?

**Comment by felixarntz** [comment]
This may have been an older issue indeed, I don't think it's relevant anymore. I believe this at least partially related to the scripts in `package.json` hard-coding `plugin-check`, but that's already been replaced with a dynamic `basename` command to get the correct directory name.

**Comment by davidperezgar** [comment]
Ok! nice!
