### ISSUE TITLE
Incorrect activation of all plugins during runtime check

### ISSUE THREAD

**Issue by mukeshpanchal27** [10up/plugin-check#184]
### Is your enhancement related to a problem? Please describe.

Currently, during the runtime check process in the Plugin Check plugin, a new database is created, and all plugins that are active on the main site are also activated in the new database. However, the desired behavior is to activate only the specific plugin that is being checked.

We have observed instances where the runtime check for Plugin X reports an error triggered by Plugin Y. This indicates that the activation of all plugins is causing conflicts and false error reports.

Plugin Code: https://github.com/10up/plugin-check/blob/trunk/includes/Checker/Runtime_Environment_Setup.php#L34-L44

@jjgrainger @felixarntz @joemcgill Please provide your feedback and suggestions on this approach.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jjgrainger** [comment]
@mukeshpanchal27 could you provide details on how to recreate the issue you are reporting here?

The `update_option` was added to fix a previous issue https://github.com/10up/plugin-check/issues/134

In addition, we have the [`Force_Single_Plugin_Preparation`](https://github.com/10up/plugin-check/blob/trunk/includes/Checker/Preparations/Force_Single_Plugin_Preparation.php) that filters the active plugins so only the plugin being tested and the plugin check are the only active plugins. So no other plugins should be reporting issues here.

If you can provide steps to reproduce the issue we could investigate further. Thanks

**Comment by felixarntz** [comment]
@mukeshpanchal27 Could you please follow up here to clarify the problem and how to replicate it (see https://github.com/10up/plugin-check/issues/184#issuecomment-1573519210)? Also, from what you're describing this sounds more like a bug to me than an enhancement?

**Comment by mukeshpanchal27** [comment]
@jjgrainger @felixarntz Follow the steps below to replicate the issue:

1. Install and activate the `Jetpack` and `Elementor` plugins.
2. Run checks for the Jetpack plugin.
3. You will find the reported error on #185.
4. The error originates from the Elementor plugin, not Jetpack.

**Comment by swissspidy** [comment]
We made some changes to the `active_plugins` filtering recently. Is this still valid?

**Comment by felixarntz** [comment]
I'm not sure how this would happen. Yes, in certain scenarios (e.g. WP-CLI, see https://docs.google.com/document/d/1wDGZBwWB2WAxfbHE3lygIzQFK8IssCa5apOyaBolukQ/edit?disco=AAABUy8TaSI), the separate DB tables will include all active plugins on the main site, but the `active_plugins` filter itself is still ensuring that only the relevant plugins are active afterwards.

I'm not aware of any bug in the filtering that would lead to all plugins from the DB remaining active.

**Comment by swissspidy** [comment]
Can't reproduce
