### ISSUE TITLE
Drop-ins should not show in plugin list

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#199]
### Describe the bug

Drop-ins like object cache should not dropdown. 

### Steps to Reproduce

1. Install an object cache plugin. 
2. Activate plugin check. 
3. Go to plugin check screen. 
4. Click on dropdown. 

### Screenshots, screen recording, code snippet

<img width="412" alt="Screenshot 2023-06-21 at 15 16 30" src="https://github.com/10up/plugin-check/assets/237508/35aef8d4-758d-4075-b2f9-c7f35d362f43">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spacedmonkey** [comment]
@felixarntz @jjgrainger @mukeshpanchal27 Is this an expected behaviour?

**Comment by felixarntz** [comment]
@spacedmonkey No, drop-ins should not show up in that list.

**Comment by spacedmonkey** [comment]
Seems like this just the copy of the drop-in the performance plugin. 

<img width="1454" alt="Screenshot 2023-06-21 at 16 05 25" src="https://github.com/10up/plugin-check/assets/237508/59f2f783-af4c-40cc-b3ac-b542119e5325">

**Comment by mukeshpanchal27** [comment]
Thank you, @spacedmonkey, for raising the issue.

Regarding the `Plugin Check Object Cache Drop-In`, it is not a drop-in itself. It is a file of the Plugin Checker plugin located at the root, which can be found here: https://github.com/10up/plugin-check/blob/trunk/object-cache.copy.php. Additionally, I checked the [Performance Lab](https://wordpress.org/plugins/performance-lab/) plugin, but the drop-in is not displayed in the dropdown for Plugin Check.

**Comment by jjgrainger** [comment]
@mukeshpanchal27 I imagine the solution for the plugin checker drop-in file is to move it into a sub-folder, but we should also test with other drop-ins to make sure they do not show either.

**Comment by felixarntz** [comment]
> @mukeshpanchal27 I imagine the solution for the plugin checker drop-in file is to move it into a sub-folder, but we should also test with other drop-ins to make sure they do not show either.

@jjgrainger Good idea, let's try that.
