### ISSUE TITLE
Test Infrastructure with PHPUnit

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#2]
## Description

Setup test infrastructure with PHPUnit

## Acceptance Criteria

- Install the following packages with composer:
    - `"phpunit/phpunit"`
    - `"squizlabs/php_codesniffer"`
    - `"wp-coding-standards/wpcs"`
- Create a `phpunit.xml.dist` file to run tests from the `/tests` folder
- Create a `phpcs.xml.dist` file to run PHPCS tests
- Update `composer.json` with the following `scripts`:
   - `"lint": "phpcs --standard=phpcs.xml.dist"` - to run PHPCS
   - `"test": "phpunit -c phpunit.xml.dist --verbose"` - to run PHPUnit tests
- Install the following packages as dev dependencies with npm
   - `@wordpress/env`
   - `@wordpress/scripts`
- Update `package.json` with the following `scripts`:
   - `"wp-env": "wp-env"` 
   - `"lint-php": "wp-env run composer run-script lint"`
   - `"test-php": "wp-env run phpunit 'phpunit -c /var/www/html/wp-content/plugins/performance/phpunit.xml.dist --verbose'"`
   - `"lint-js": "wp-scripts lint-js ./bin"`
- Create the following GitHub workflows in the `.github/workflows/` folder. (See [Performance Lab Plugin](https://github.com/WordPress/performance/tree/trunk/.github/workflows) for examples)
   - `js-lint.yml`
   - `php-lint.yml`
   - `php-test.yml`

**Comment by felixarntz** [comment]
@jjgrainger I think we should also include running linting and tests in CI here. This would entail:
* Add `package.json` with `@wordpress/env` dependency and relevant scripts, e.g. `lint-php` and `test-php` like in https://github.com/WordPress/performance/blob/trunk/package.json.
* A `.wp-env.json` file like https://github.com/WordPress/performance/blob/trunk/.wp-env.json.
* GitHub action workflows for linting PHP and running PHPUnit tests, which could probably almost entirely copied over from the Performance Lab plugin as well.

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

I've updated to include the items you've raised and referenced the Performance Lab plugin as an example.

**Comment by felixarntz** [comment]
@jjgrainger ACs LGTM, except I don't think we need the `js-lint` part. Not sure there will be any JS in that repository anytime soon, I think we can skip that for now. This is a minor detail though, so moving this into _To Do_.

**Comment by aaemnnosttv** [comment]
> Not sure there will be any JS in that repository anytime soon, I think we can skip that for now. 

@felixarntz what about for the admin screen and ajax checks?
