### ISSUE TITLE
Create Late_Escaping_Check

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#20]
## Description

Checks that proper [escaping functions](https://developer.wordpress.org/plugins/security/securing-output/) are used correctly within templates. This is a security check to ensure that any variables that are output within templates are stripped of any unwanted data such as malformed HTML or scripts. This will use the existing `WordPress.Security.EscapeOutput` sniff in the [VIP Coding Standards](https://github.com/Automattic/VIP-Coding-Standards).

## Acceptance Criteria

- Class `Late_Escaping_Check` should be created and exists at `includes/Checker/Checks`
- Class `Late_Escaping_Check` should extend the `Abstract_PHP_CodeSniffer_Check` abstract class
- Class should implement the protected `get_args()` and return an associative array of the required PHPCS arguments
    - `'sniffs' => 'WordPress.Security.EscapeOutput'`
    - `'standard' => 'WordPress'`
- A new test plugin should be created at `tests/phpunit/testdata/plugins/test-plugin-late-escaping/`
    - The test plugin will contain code that will trigger n error when the check is run.
 
## Tests Coverage
- `run()` method adds an error to the `$check_result` when checking an invalid file - check reference [here](https://github.com/10up/plugin-check/blob/trunk/tests/Checker/Checks/I18n_Usage_Check_Tests.php#L20)
- `run()` method does not add any warnings or errors to the `$check_result` when checking a valid file - check reference [here](https://github.com/10up/plugin-check/blob/trunk/tests/Checker/Checks/I18n_Usage_Check_Tests.php#L51)

**Comment by vishalkakadiya** [comment]
@felixarntz I have updated AC for this issue, it is ready for your review now. Thank you! 🙂

**Comment by eclarke1** [comment]
Unassigning @felixarntz as we need to have a new check on the ACs here given the recent changes and the fact this is now part of our new milestone 2 scope. Moving back to Definition to adjust the AC and estimate if required. cc @jjgrainger @mukeshpanchal27

**Comment by jjgrainger** [comment]
@felixarntz @mukeshpanchal27 I've updated the AC's and this is ready for review

**Comment by mukeshpanchal27** [comment]
Thanks @jjgrainger, The AC look good to me.

**Comment by felixarntz** [comment]
@jjgrainger ACs LGTM!

Nit-pick:
> The test plugin will contain code that will trigger a warning when the check is run.

This is probably an error rather than a warning, or not?

**Comment by jjgrainger** [comment]
@felixarntz yes, as it is a security check is should be an error. I've updated the AC's and will pick this one up.
