### ISSUE TITLE
User should not be able to change dropdown while running check

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#201]
### Is your enhancement related to a problem? Please describe.

When a user starts a plugin check, they should not be able to change the dropdown to another plugin. This is confusing UX. 

Couple of things could fix this. 

1. When check is running, disable the dropdown. 
2. Check the plugin is changed, the current check should be disabled. 

https://github.com/10up/plugin-check/assets/237508/969a7b41-2a60-43e6-ac4e-60a705cdd2e8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mukeshpanchal27** [comment]
Thank you, @spacedmonkey, for bringing up the issue.

Great observation! We can include the `disabled` attribute in the select element while the checks are running, and remove it once they have completed.

<img width="534" alt="Screenshot 2023-06-22 at 2 09 06 PM" src="https://github.com/10up/plugin-check/assets/10103365/4f54ad7a-47fc-4767-bc24-28f5fc52100e">

cc. @felixarntz @jjgrainger

**Comment by felixarntz** [comment]
Good catch @spacedmonkey! I just added the bug and WP Admin labels, would be great if you could add labels as needed in the future.

**Comment by mukeshpanchal27** [comment]
@spacedmonkey, we have addressed this issue in #212. Please consider this as resolved. If needed, feel free to reopen the issue.
