### ISSUE TITLE
Allow running only checks of certain categories in WP Admin & WP-CLI

### ISSUE THREAD

**Issue by felixarntz** [10up/plugin-check#206]
### Is your enhancement related to a problem? Please describe.

⚠️  **Follow up to / blocked by #203**

Once the foundation for check categories has been implemented, this issue here should be used to expose (optionally) setting one or more categories to run checks for in WP Admin and WP-CLI.

#### For WP-CLI
* Add a new optional parameter `--categories` which expects a comma separated list of category slugs.
* If passed, only checks that fall in one of the categories should be run. Otherwise (default), all checks should be run.

#### For WP Admin
* Add a new `fieldset` with checkboxes for every available category to the WP Admin screen. By default, all of them should be checked.
* The categories checked should be passed along in the AJAX request to get the checks to run, and only checks that fall in one of the categories should be returned.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felixarntz** [comment]
cc @spacedmonkey as this is something you were interested in

**Comment by jjgrainger** [comment]
Thanks @felixarntz AC's look good to me

**Comment by mukeshpanchal27** [comment]
Thanks @felixarntz AC's look good to me. Do we have any UI design for the WP Admin or we can make it simple? cc. @eclarke1

**Comment by felixarntz** [comment]
@mukeshpanchal27 I'd suggest we stick with a regular `fieldset` and check boxes, let's look at some of the relevant WP core settings screens that have such a UI element and style them in a similar way.
