### ISSUE TITLE
Implement check to avoid localhost usage

### ISSUE THREAD

**Issue by felixarntz** [10up/plugin-check#207]
### Is your enhancement related to a problem? Please describe.

See https://github.com/WordPress/plugin-check/blob/trunk/checks/localhost.php, which was recently implemented. We should implement a corresponding check in our tool.

### Designs

* Reimplement the check from https://github.com/WordPress/plugin-check/blob/trunk/checks/localhost.php by extending `Abstract_File_Check`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mukeshpanchal27** [comment]
Thanks @felixarntz, ACs look good to me.
