### ISSUE TITLE
Implement check to avoid `ALLOW_UNFILTERED_UPLOADS` usage

### ISSUE THREAD

**Issue by felixarntz** [10up/plugin-check#208]
### Is your enhancement related to a problem? Please describe.

See https://github.com/WordPress/plugin-check/blob/allow_unfiltered_uploads-check/checks/check-constants.php, let's implement this as a more specific `No_Unfiltered_Uploads_Check` for now.

### Designs

* Reimplement the above by extending `Abstract_File_Check`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mukeshpanchal27** [comment]
Thanks @felixarntz, ACs look good to me.
