### ISSUE TITLE
CLI Command shows critical error

### ISSUE THREAD

**Issue by mukeshpanchal27** [10up/plugin-check#210]
### Describe the bug

After implementing the `Performant_WP_Query_Params_Check()` check #27, the CLI command now displays a critical error when executed.

Command: `npm run wp-env run cli -- wp plugin check hello.php --require=./wp-content/plugins/plugin-check/cli.php`

### Steps to Reproduce

1. Open terminal
2. Go to /plugin-check folder
3. Run `npm run wp-env run cli -- wp plugin check hello.php --require=./wp-content/plugins/plugin-check/cli.php` in your command promp

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felixarntz** [comment]
@mukeshpanchal27 What is the critical error? Could you share that here please?

**Comment by mukeshpanchal27** [comment]
@felixarntz, when I run the command `npm run wp-env run cli -- wp plugin check hello.php --require=./wp-content/plugins/plugin-check/cli.php` through the CLI, it displays an error as shown in the attached image.

**Error Image:**
<img width="1050" alt="Screenshot 2023-06-28 at 10 17 48 AM" src="https://github.com/10up/plugin-check/assets/10103365/56744799-3f60-4d9b-b312-21567e5aca4f">

After debugging the issue, I have identified that it is related to the PHPCS arguments that we previously fixed for unit tests in the pull request https://github.com/10up/plugin-check/pull/186/commits/6ddb6056d8ea7f12621f6ba2ed779f94d69d0ad5. I will open a pull request soon to address this issue.

**Comment by felixarntz** [comment]
@mukeshpanchal27 That error is only showing the generic error message of WordPress when any fatal error happens. Can you please share the actual error? You can probably get it from the debug.log referenced at the bottom.

I'm asking since I would like to get more context on #214.

**Comment by mukeshpanchal27** [comment]
Apologies, @felixarntz, for forgetting to mention the updates I made in the PR description.
