### ISSUE TITLE
Remove `Check this plugin` action link from Drop-ins and MU Plugins

### ISSUE THREAD

**Issue by mukeshpanchal27** [10up/plugin-check#218]
### Describe the bug

I discovered an issue with the "Check this plugin" action link in the Plugin Checker feature. Currently, this action link is available for the Drop-ins and MU Plugins, but it is unusable as we are unable to test the Drop-ins and MU Plugins functionality. To enhance the usability and overall user experience, I suggest removing the "Check this plugin" action link from the Drop-ins and MU Plugins.

Related: #213

### Steps to Reproduce

1. Go go Admin Panel
2. Install and activate plugin which generate Drop-ins (Performance Lab Or Query Monitor)
3. Go to `/wp-admin/plugins.php?plugin_status=dropins` or `/wp-admin/plugins.php?plugin_status=mustuse`
4. `Check this plugin` action link present.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mukeshpanchal27** [comment]
@felixarntz, should we prioritize this small bug for Milestone 2? cc. @eclarke1 @jjgrainger @spacedmonkey

**Comment by felixarntz** [comment]
@mukeshpanchal27 Good catch, and yeah let's include a fix in Milestone 2. That leads me to another question: Have you already checked the other kinds of plugins? For example, for MU plugins we need to make sure that the link isn't displayed either.

**Comment by mukeshpanchal27** [comment]
@felixarntz, I have also verified the same for the MU Plugin, and I noticed that the "Check this plugin" action link is present there as well. Therefore, I have updated the issue details to reflect this information, and we can address both issues in a single pull request.

**Comment by felixarntz** [comment]
Thanks @mukeshpanchal27, LGTM!
