### ISSUE TITLE
Create Enqueued_Scripts_In_Footer_Check

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#22]
Create Enqueued_Scripts_In_Footer_Check class, and this class will basically warn for following things:

- Checks registered and enqueued scripts in the plugin and warn if the $in_footer parameter is false, It is encouraged that any non-essential scripts are loaded in the footer to prevent render-blocking on the page.
- It will also check that the version parameter is set to a non-falsy value. Using versions in the scripts can be beneficial for performance and cache busting.

This will use the existing WordPress.WP.EnqueuedResourceParameters sniff in the [WordPress Coding Standards](https://github.com/WordPress/WordPress-Coding-Standards/).

## Acceptance Criteria

- Class `Enqueued_Scripts_In_Footer_Check` should be created and exists at `includes/Checker/Checks`
- Class `Enqueued_Scripts_In_Footer_Check` should extend the `Abstract_PHP_CodeSniffer_Check` abstract class
- Class should implement the public `get_args()` and return an associative array of the required PHPCS arguments
    - `'sniffs' => 'WordPress.WP.EnqueuedResourceParameters'`
    - `'standard' => 'WordPress'`
- A sample code snippet should be added to the `tests/testdata/plugins/test-plugin-enqueued-scripts-in-footer-check-with-errors/load.php` file, which triggers the `WordPress.WP.EnqueuedResourceParameters` error. The following code can be used as an example:

```
add_action(
	'wp_enqueue_scripts',
	function() {
		wp_enqueue_script(
			'plugin_check_header_script',
			plugin_dir_url( __FILE__ ) . 'header.js'
		);
	}
);
```
- Another sample code snippet should be added to the `tests/testdata/plugins/test-plugin-enqueued-scripts-in-footer-check-without-errors/load.php` file, which does not trigger any errors. The code snippet can be as follows::

```
add_action(
	'wp_enqueue_scripts',
	function() {
		wp_enqueue_script(
			'plugin_check_footer_script',
			plugin_dir_url( __FILE__ ) . 'footer.js',
			array(),
			'1.0.0',
			true
		);
	}
);
```

## Tests Coverage
- The `test_run_with_errors()` method should verify that errors are returned when running the check.
- The `test_run_without_errors()` method should confirm that no errors are returned when running the check.

**Comment by vishalkakadiya** [comment]
@felixarntz I have updated AC for this issue. It is ready for review now. Thanks! 🙂

**Comment by eclarke1** [comment]
Unassigning @felixarntz as we need to have a new check on the ACs here given the recent changes and the fact this is now part of our new milestone 2 scope. Moving back to Definition to adjust the AC and estimate if required. cc @jjgrainger @mukeshpanchal27

**Comment by mukeshpanchal27** [comment]
Hi @jjgrainger @felixarntz I have updated the AC's and are ready for you to review. Thanks!

cc. @joemcgill

**Comment by felixarntz** [comment]
@mukeshpanchal27 ACs LGTM!

For the future, no need to include code in the ACs. It's a bit more efficient to limit it to an explanation rather than code written.
