### ISSUE TITLE
Show message if plugin is run in production envoriment

### ISSUE THREAD

**Issue by spacedmonkey** [10up/plugin-check#223]
### Is your enhancement related to a problem? Please describe.

An idea that come out of a developer chat. 

Show a error or warning message on the plugin check screen, to inform users that is not recommended to run the plugin checker on a production / live server. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by swissspidy** [comment]
Were you thinking of `wp_get_environment_type()` or something else?

**Comment by mukeshpanchal27** [comment]
Thank you, @spacedmonkey, for opening the issue.

> Were you thinking of `wp_get_environment_type()` or something else?

The function always return `production` if users did not set it.

In my opinion, the plugin should be safe to use with static checks. However, there may be some disruptions when it comes to runtime checks. In such cases, I propose the following approach to allow the plugin to be used in a production environment:

- When the plugin is activated, both static and runtime checks will be performed. At this point, a JavaScript prompt can be displayed with a message advising users not to perform check in production environment.
- When the plugin is deactivated, only static checks will be performed, and no message will be displayed.

I understand that many sites do not have a separate development version, and they rely on the plugin checker tool. This approach aims to strike a balance between usability and caution by providing a warning during plugin activation while still allowing for static checks to be performed in a production environment.

cc. @felixarntz @joemcgill @eclarke1

**Comment by swissspidy** [comment]
> I understand that many sites do not have a separate development version, and they rely on the plugin checker tool. 

I doubt that _developers_ who develop a plugin and use Plugin Check for it do so an a production environment.

**Comment by davidperezgar** [comment]
Yes, I don't see developers using in production site.

**Comment by jeffpaul** [comment]
@swissspidy I'd recommend reconsidering this as I expect it to be entirely likely that site owners use this to check the "quality" of plugins in use on their site or perhaps use to compare various plugins and do so on a production site.  As such, some messaging to recommend against that seems wise.
