### ISSUE TITLE
Create Enqueued_Scripts_Scope_Check

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#23]
## Description

Checks that scripts are only enqueued in certain contexts and not just everywhere. While a theme often enqueues scripts or styles that are needed for the entire site, plugins usually have specific behaviors that often do not affect the entire site. Such plugins should not just call wp_enqueue_script() on the wp_enqueue_scripts action, but have conditional logic in there to only enqueue the script when needed based on context. This check would load different contexts (simulating different URLs) of different kinds and warn if a script is enqueued on all of them.

## Acceptance Criteria

- Class `Enqueued_Scripts_Scope_Check ` should be created and exists at `includes/Checker/Checks`
- Class `Enqueued_Scripts_Scope_Check ` should extend the `Runtime_Check` abstract class which extends `Check` interface
- Property `$violation` code should be `warning`
- Method `run` should be implemented from the `Runtime_Check` abstract class if needed
- `Check_Result $check_result` should be used from the `run` method parameter to append the results

## Test Coverage

- `Enqueued_Scripts_Scope_Check ` class is expected to extend `Runtime_Check` class
- `Enqueued_Scripts_Scope_Check ` class is expected to be instance of `Runtime_Check` class
- `run` method expected to append the audit results to `$check_result`

**Comment by swissspidy** [comment]
For the start I suppose we can just copy `Enqueued_Styles_Scope_Check` for scripts.
