### ISSUE TITLE
Create Enqueued_Styles_Scope_Check

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#24]
## Description

Checks that styles are only enqueued in certain contexts and not just everywhere. This is the same as the [Enqueued_Scripts_Scope_Check](https://github.com/10up/plugin-check/issues/23) only for stylesheets instead of scripts.

## Acceptance Criteria

- Class `Enqueued_Styles_Scope_Check` should be created and exists at `includes/Checker/Checks`
- Class `Enqueued_Styles_Scope_Check` should extend the `Abstract_Runtime_Check` class.
- Class `Enqueued_Styles_Scope_Check` will use the `URL_Aware` trait.
- Class `Enqueued_Styles_Scope_Check` will implement the`With_Shared_Preparations` interface.
- A `prepare()` method will be implemented in the class.
    - This method will save the `$GLOBALS['wp_styles'];` to a temporary variable.
    - Then set the `$GLOBALS['wp_styles'];` to null if set.
    - A clean up function is returned which uses the temporary variable to reinstate the original `$GLOBALS['wp_styles'];` value.
- A `get_shared_preparations()` method will be implemented.
    - The `get_shared_preparations()` method will be used to return a preparation that creates a demo post for all publicly viewable post types.
    - The method will return an array where the `Demo_Post_Creation_Preparation` class name is an array key and it's value is an array of posts data to create, compatible with [`wp_insert_post`](https://developer.wordpress.org/reference/functions/wp_insert_post/).
- A protected `get_urls()` method will be created.
    - The method will return an array of URLs containing the home URL and URLs for all publicly viewable post types.  
- Method `run( Check_Result $results )` should be implemented from the `Runtime_Check` abstract class.
    - The `run()` method will call the `run_for_urls()` method passing an array of URLs returned by the `get_urls()` method, a callable which will be the classes `check_url()` method, and the `Check_Results` instance.
    -  The `Check_Result $check_result` will be returned by the `run` method.
- A protected `check_url()` method will be created.
    - The method will accept an instance of the `Check_Result` class and a URL string as parameters.  
    - The method will reset the `$GLOBALS['wp_styles'];`
    - Then will call the `wp_enqueue_scripts()` to enqueue all of the checked plugins styles.
    - Using the object returned by `wp_styles()` all enqueued styles for the URL will be looped over:
        - Check the style is part of the plugin being checked by matching the plugin URL with the style URL
        - It will return styles that print in all pages.
        - Return notice with the message.

## Tests Coverage
- `Enqueued_Styles_Scope_Check` class is expected to extend `Runtime_Check` class
- `Enqueued_Styles_Scope_Check` class is expected to be instance of `Runtime_Check` class
- `run` method expected to append the audit results to `$check_result`

**Comment by mukeshpanchal27** [comment]
@felixarntz @jjgrainger I've updated the AC's and this is ready for review. Thanks!

cc. @eclarke1 @joemcgill

**Comment by felixarntz** [comment]
@mukeshpanchal27 ACs LGTM!

Just to clarify the message type, a _warning_ should be used for any stylesheet present in all URLs.
