### ISSUE TITLE
Achieve check feature parity with plugin review team's current tool

### ISSUE THREAD

**Issue by felixarntz** [10up/plugin-check#253]
### Is your enhancement related to a problem? Please describe.

Reviewing https://github.com/WordPress/plugin-check/commits/trunk, several check related changes have landed in the past 2 weeks that should be incorporated into our plugin checker for parity.

Each of the below top-level bullet points should preferably be addressed in its own PR:
* [x] Update severity of certain checks in `Plugin_Readme_Check` to "error" (see https://github.com/WordPress/plugin-check/commit/c5d539b6d248dba81fcbb2218207c7302aaf91c4).
* [x] Update Plugin Check Review PHPCS XML file related to `Plugin_Review_PHPCS_Check` with latest changes from https://github.com/WordPress/plugin-check/commit/593983160d936e35369930a3a1b07d3dbb538e6e, https://github.com/WordPress/plugin-check/commit/ee56bc209ffca0f552fde9e8da18de9356816d65, and https://github.com/WordPress/plugin-check/commit/542ea3c704f1886237db86a832bb64fac0cea6e2.
* [x] Add application files support to `File_Type_Check` (see https://github.com/WordPress/plugin-check/commit/b081cf7aa0ccc32e158d803b8905a66914c3f086).
* [x] Implement new check for plugin trademark violations (see https://github.com/WordPress/plugin-check/commit/f15d41c26ece3cc760c90e87aaf4a4966b873784).

cc @eclarke1 @joemcgill @bordoni

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bordoni** [comment]
Thank you for logging this here.
I will start porting over the code into the branch later today, so we can reference the old code from this repo.

**Comment by bordoni** [comment]
All of the code from our legacy plugin repository is now living here on the [`legacy-plugin`](https://github.com/10up/plugin-check/tree/legacy-plugin) branch.

_Sorry for the random mentions that were made once the commits were ported, since the hashtag mentions were to the old issues and PRs._

I will manually release version `0.2.0` this week to the WP.org, once we the Plugin Review team is ok with a launch date.

**Comment by bordoni** [comment]
We are live with version `0.2.0` on WordPress.org.

https://wordpress.org/plugins/plugin-check/

**Comment by mukeshpanchal27** [comment]
@felixarntz, I am closing this issue as we have successfully merged all the top-level bullet point changes into the trunk.
