### ISSUE TITLE
Create Image_Functions_Usage_Check

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#26]
## Description

Checks and warns against the usage of image HTML in templates. Developers are encouraged to use image functions such as wp_get_attachment_image that generate image HTML in templates. The HTML output by these functions is often better as it generates the tag with more performant attributes such as srcset and sizes. No existing sniff exists but the existing WordPress.WP.EnqueuedResources sniff in the [WordPress Coding Standards](https://github.com/WordPress/WordPress-Coding-Standards/) can be used as a starting point.

## Acceptance Criteria

- Class `Image_Functions_Usage_Check` should be created and exists at `includes/Checker/Checks`
- Class `Image_Functions_Usage_Check` should extend the `PHPCodesniffer_Check` abstract class which extends `Check` interface
- Property `$violation` code should be `warning`
- Method `run` should be implemented from the `PHPCodesniffer_Check` abstract class if needed
- `Check_Result $check_result` should be used from the `run` method parameter to append the results
- `$_SERVER['argv']` arguments should be passed to parent `run` method to provide PHPCS information about `standard`, `report` and `sniff`
- Custom sniff to detect the non-usage of wp image functions 

## Tests Coverage
- `Image_Functions_Usage_Check` class expected to extend `PHPCodesniffer_Check` abstract class
- `Image_Functions_Usage_Check` class expected to be instance of the `PHPCodesniffer_Check` class
- `run` method expected to append results of check into `$check_result`

**Comment by swissspidy** [comment]
This should be trivial to implement by following the [`EnqueuedResourcesSniff`](https://github.com/WordPress/WordPress-Coding-Standards/blob/2133137c33fa898df70b5f879a65d83af4dbb97d/WordPress/Sniffs/WP/EnqueuedResourcesSniff.php) implementation, but we need a good regex and a good documentation. Is `wp_get_attachment_image` the only function to recommend here?

**Comment by swissspidy** [comment]
From #443:

> `Image_Functions_Usage_Check`: Would warn about any direct output of `img` tags in PHP code and templates, as those should use `wp_get_attachment_image()` etc. instead, which comes with performance benefits. The exception is `img` tags which aren't for attachments. For such manual `img` tags, the check could trigger a warning if the `wp_get_loading_optimization_attributes()` is not used as part of generating the output.

For the last part about `wp_get_loading_optimization_attributes()` I am not sure how feasible that actually is. Maybe just something for the documentation for now.
