### ISSUE TITLE
<pre> tags do not wrap properly in the PHPCS errors

### ISSUE THREAD

**Issue by EvanHerman** [10up/plugin-check#263]
### Describe the bug

The `<pre>` tags do not wrap properly and extend beyond the width of the browser window.

### Steps to Reproduce

1. Go to the plugin check page and run the plugin check on a plugin with a PHPCS warning or error.
2. If the text doesn't extend beyond the width of the error div then zoom in on the browser (command and + on a mac).
3. Continue to zoom in until the text extends beyond the width of the browser.

### Screenshots, screen recording, code snippet

<img width="1438" alt="image" src="https://github.com/10up/plugin-check/assets/5321364/61dfb1ff-a559-4b41-b577-3d0806a89cd1">

<img width="1235" alt="image" src="https://github.com/10up/plugin-check/assets/5321364/8c5a34d0-2ba8-4c49-b886-b5f96db55603">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bordoni** [comment]
Resolved by #264
