### ISSUE TITLE
Improve readme file with step guide

### ISSUE THREAD

**Issue by vapvarun** [10up/plugin-check#268]
### Is your enhancement related to a problem? Please describe.

I am grateful to everyone who created the much-needed plugin checker.
The first expression after installing the plugin is https://prnt.sc/srCMkVAJuR8b when testing any plugin.
We can also include the following steps in the readme file
cd wp-content/plugins/plugin-check
composer install
npm install

It seems that the steps mentioned above are not included in the description on WP.org's readme.
https://wordpress.org/plugins/plugin-check 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bordoni** [comment]
Thank you so much for reporting the issue.

This problem was resolve by #259. We will likely launch version `0.2.1` early next week with the fix. Closing the issue.

**Comment by vapvarun** [comment]
@bordoni, it was specific to adding instructions to the readme.txt file, as the readme.txt file controls the output on the front-facing part of the directory. Like [[README.md](https://github.com/10up/plugin-check#readme)](https://github.com/10up/plugin-check/blob/trunk/README.md), we have detailed info in this file. 
Without executing
```
composer install
npm install
```
these commands in wp-content/plugins/plugin-check directory, they will not be able to test their plugins.
