### ISSUE TITLE
Create Performant_WP_Query_Params_Check

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#27]
## Description

Checks for the usage of non-performant `WP_Query` arguments. These will include sniffs that check and warn for use of arguments such as:

- `post__not_in`
- passing `posts_per_page => -1` or a high limit above a threshold
- passing `cache_results => false`.
- usage of `meta_query` and `term_query` keys.

This will use the existing `WordPressVIPMinimum.Performance.WPQueryParams` sniff in the [VIP Coding Standards](https://github.com/Automattic/VIP-Coding-Standards) and the `WordPress.DB.SlowDBQuery` sniff in the [WordPress Coding Standards](https://github.com/WordPress/WordPress-Coding-Standards/).

## Acceptance Criteria

- Class `Performant_WP_Query_Params_Check` should be created and exists at `includes/Checker/Checks`
- Class `Performant_WP_Query_Params_Check` should extend the `Abstract_PHP_CodeSniffer_Check` abstract class
- Class should implement the public `get_args()` and return an associative array of the required PHPCS arguments
    - `'sniffs' => 'WordPress.DB.SlowDBQuery, WordPressVIPMinimum.Performance.WPQueryParams'`
    - `'standard' => 'WordPress,WordPressVIPMinimum'`
- A new test plugin should be created at `tests/phpunit/testdata/plugins/test-plugin-performant-wp-query-params/`
    - Test plugin should contain code to trigger a warning in the check using the following code.

```
    $query = new WP_Query(
         array(
		'post__not_in'   => array( 1, 2, 3 ),
		'posts_per_page' => -1,
		'cache_results'  => false,
		'meta_key'       => 'age',
		'meta_query'     => array(
			array(
				'key'     => 'age',
				'value'   => array( 3, 4 ),
				'compare' => 'IN',
			),
		),
		'tax_query'      => array(
			array(
				'taxonomy' => 'custom_taxonomy_slug',
				'operator' => 'EXISTS',
			),
		),
	  )
    );
```

## Tests Coverage
- `run()` method adds warnings to the `$check_result` when checking an invalid file - check reference [here](https://github.com/10up/plugin-check/blob/trunk/tests/Checker/Checks/I18n_Usage_Check_Tests.php#L20)
- `run()` method does not add any warnings to the `$check_result` when checking a valid file - check reference [here](https://github.com/10up/plugin-check/blob/trunk/tests/Checker/Checks/I18n_Usage_Check_Tests.php#L51)

**Comment by vishalkakadiya** [comment]
@felixarntz I have updated AC for this issue, and it is ready for your review now. Thanks!

**Comment by spacedmonkey** [comment]
I would also love to see checks for 

update_post_meta_cache
update_post_term_cache
lazy_load_term_meta
ignore_sticky_posts
nopaging
no_found_rows

These params can effect performance.

**Comment by felixarntz** [comment]
Thanks @spacedmonkey, those are great ideas.

Just for transparency, those additional checks are currently on the backburner as we're focused on completing the infrastructure at this point. So it may take a bit until we continue on the checks issues like this one.

**Comment by spacedmonkey** [comment]
No rush, just reviewing the tickets in the backlog and felt a note while I remembered.

**Comment by eclarke1** [comment]
Unassigning @felixarntz as we need to have a new check on the ACs here given the recent changes and the fact this is now part of our new milestone 2 scope. Moving back to Definition to adjust the AC and estimate if required. cc @jjgrainger @mukeshpanchal27

**Comment by jjgrainger** [comment]
@felixarntz @mukeshpanchal27 I have updated the AC's and is ready for your review.

cc @eclarke1

**Comment by felixarntz** [comment]
@jjgrainger ACs LGTM!

Note though that the `WordPressVIPMinimum` is not part of our codebase yet, so it may be worth clarifying that it'll need to be added as a new dependency.
