### ISSUE TITLE
checks/readme.php missing translation functions

### ISSUE THREAD

**Issue by pixolin** [10up/plugin-check#270]
### Describe the bug

After translating the plugin into German, part of the test results is shown in English. It seems, the file `check/readme.php` is missing translation functions. Unfortunately I couldn't find this plugin file in the repo and therfor can't submit a pull request.

![screenshot_000842@2x](https://github.com/10up/plugin-check/assets/1968542/70115bf1-8dd6-4d40-bd84-3cbba01b3fb9)

### Steps to Reproduce

Activate plugin in WordPress with language set to German.

### Screenshots, screen recording, code snippet

see above

### Environment information

MacOS Ventura, Firefox

### WordPress information

WordPress 6.3.1, plain vanilla test environment.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bordoni** [comment]
Thank you for the report. I will tackle that.
It was in a separate branch `legacy-plugin`, it's a bit messy for now but it will eventually be cleaned up to be all in trunk.
