### ISSUE TITLE
Plugin check reports that readme.txt is missing

### ISSUE THREAD

**Issue by dev4press** [10up/plugin-check#271]
### Describe the bug

When scanning the plugin (and that is any plugin), one of the last reported errors is that readme.txt file is missing. I have attached the screenshot of the results I get. I am using the latest plugin-check version downloaded imported from GitHub.

### Steps to Reproduce

1. Open the Tools -> Plugin Check.
2. Select any plugin and click Check It button
3. All 5 categories to check and enabled.

### Screenshots, screen recording, code snippet

![plugin-check-bbpress-readme](https://github.com/10up/plugin-check/assets/337934/1c0f4b25-ad65-4a21-9eef-0e03ccfde11c)

I have edited the results to only show the error with readme file.the 

### Environment information

 - OS: MS Windows 11 22H2
 - Environment: Laragon
 - Server: Apache 2.4.55 64bit
 - PHP: 7.4.33 or 8.2.10

### WordPress information

- WordPress 6.3.1
- No plugins except the plugin-check are active

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bordoni** [comment]
The Version downloaded from GitHub and the one used on WordPress.org, for a while they will be diff versions. The version you are using is the version of the plugin used by the Performance team not the Plugin Review team.

Eventually they will be one and the same, but we have some refactoring and cleanup before that can be the case.

Please test with the WP.org version.

**Comment by dev4press** [comment]
The plugin download from WP.org for me, doesn't work at all, it asks to run composer install, and that is not working because the composer file is not present.

**Comment by bordoni** [comment]
That `composer install` problem will be solved later when we release `0.2.1`.
