### ISSUE TITLE
Incorrect deprecation notice for sanitize_url()

### ISSUE THREAD

**Issue by wsform** [10up/plugin-check#273]
### Describe the bug

This deprecation notice is incorrect:

_sanitize_url() has been deprecated since WordPress version 2.8.0. Use esc_url_raw() instead._

According to the documentation it was restored (un-deprecated) in version 5.9.

[https://developer.wordpress.org/reference/functions/sanitize_url/](https://developer.wordpress.org/reference/functions/sanitize_url/)

In: **DeprecatedFunctionsSniff.php**

```
    'sanitize_url' => array(
        'alt'     => 'esc_url_raw()',
        'version' => '2.8.0',
    ),
```

### Steps to Reproduce

1. Run the checks on any plugin that contains the function sanitize_url()
2. Error shown: WordPress.WP.DeprecatedFunctions.sanitize_urlFound

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by r-martins** [comment]
I've tested a plugin with sanitize_url calls and could not reproduce the error you mentioned.

Using: WP 6.3.2
Plugin check: trunk (85e2a7) n.e.x.t 

Also tested with the tag 0.2.1. Could not reproduce.

Can you send a link to the plugin you've tested and which version you used?

**Comment by swissspidy** [comment]
This might have been reported when using the (old) version from the plugin repository, but the one here in the repo does not have the same issue, because we're using WPCS 3.0 and this has been address there [a long time ago](https://github.com/WordPress/WordPress-Coding-Standards/pull/2121).
