### ISSUE TITLE
Refactoring and Code Duplication Reduction for `Plugin_Readme_Check` and `Trademarks_Check`

### ISSUE THREAD

**Issue by mukeshpanchal27** [10up/plugin-check#286]
In pull request #285, we introduced the `Trademarks_Check` check, which reuses code identical to that found in the `Plugin_Readme_Check`. This duplicate code is a potential source of maintenance challenges and can introduce bugs. It is essential that we address this issue promptly to improve the overall quality of our codebase.

**Comment by felixarntz** [comment]
Thank you for opening this @mukeshpanchal27!

Once #285 is merged, I think we can do the following:
* Introduce a trait like `Amend_Check_Result` that has two protected methods `add_result_error_for_file()` and `add_result_warning_for_file()`. This should replace the existing duplicated code across several tests.
* Introduce another trait like `Find_Readme` that has a single protected method `filter_files_for_readme()`, which filters a given `$files` array and returns the array with only `readme.txt`, or only `readme.md`, or empty array if there is no readme. This should replace the existing duplicated code across `Plugin_Readme_Check` and `Trademarks_Check`.
