### ISSUE TITLE
Create Direct_DB_Queries_Check

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#29]
## Description

Checks for direct database queries within the plugin codebase. These should be avoided as these queries can negatively impact performance and bypass inbuilt caches. This sniff will evaluate $wpdb usage and warn the developer about its use. This will use the existing `WordPress.DB.DirectDatabaseQuery` sniff in the [WordPress Coding Standards](https://github.com/WordPress/WordPress-Coding-Standards/).

## Acceptance Criteria

- Class `Direct_DB_Queries_Check` should be created and exists at `includes/Checker/Checks`
- Class `Direct_DB_Queries_Check` should extend the `Abstract_PHP_CodeSniffer_Check` abstract class
- Class should implement the public `get_args()` and return an associative array of the required PHPCS arguments
    - `'sniffs' => 'WordPress.DB.DirectDatabaseQuery'`
    - `'standard' => 'WordPress'`
- Add a sample code in the `tests/testdata/plugins/test-plugin-with-errors\test-plugin-with-errors.php` file, which will come under the `WordPress.DB.DirectDatabaseQuery` error - we can use DB query by using `$wpdb` global variable.

## Tests Coverage
- `get_args()` method returns the expected array of PHPCS arguments for the check
- `run()` method adds warnings to the `$check_result` when checking an invalid file - check reference [here](https://github.com/10up/plugin-check/blob/trunk/tests/Checker/Checks/I18n_Usage_Check_Tests.php#L20)
- `run()` method does not add any warnings to the `$check_result` when checking a valid file - check reference [here](https://github.com/10up/plugin-check/blob/trunk/tests/Checker/Checks/I18n_Usage_Check_Tests.php#L51)

**Comment by vishalkakadiya** [comment]
I'm working on updating AC for this issue. Thank you!
CC @eclarke1 @jjgrainger

**Comment by vishalkakadiya** [comment]
@felixarntz I have updated AC for this, and it is now ready for review. Thanks! 🙂
