### ISSUE TITLE
Improve behavior for single-file plugins such as `hello.php`

### ISSUE THREAD

**Issue by swissspidy** [10up/plugin-check#307]
If I run `wp plugin check hello.php` such as `no_plugin_readme` and `trademarked_term`. The latter because it thinks the slug is `plugins` (from `wp-content/plugins/hello.php`).

**Comment by mukeshpanchal27** [comment]
Well spotted, @swissspidy. I'll assign this task to myself for further examination and to work on resolving it. cc. @eclarke1 @felixarntz
