### ISSUE TITLE
WP Admin Screen - Tools page

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#31]
- [x] https://github.com/10up/plugin-check/issues/32
- [x] https://github.com/10up/plugin-check/issues/33
- [x] https://github.com/10up/plugin-check/issues/34
- [x] https://github.com/10up/plugin-check/issues/84 
- [x] https://github.com/10up/plugin-check/issues/35
- [x] https://github.com/10up/plugin-check/issues/36

**Comment by eclarke1** [comment]
@jjgrainger do you agree with closing out these [Type] Overview issues as I don't think they add much value, considering this repo is just all for plugin check, it's easier to see progress using other labels.

**Comment by jjgrainger** [comment]
@eclarke1 I agree, will close this now
