### ISSUE TITLE
Add dropdown option and display elements

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#33]
There will be a dropdown list of plugins installed on the site with a submit button to trigger checks for the plugin.

## Page form options
<img width="401" alt="Screenshot 2022-11-21 at 7 58 21 PM" src="https://user-images.githubusercontent.com/4090336/203079901-f98a997e-f80e-413a-b8e3-4fc32acab9ab.png">

## Acceptance Criteria

- In the `Admin` class, we need to use the `get_plugins` function to get a list of all the activated plugins, exclude `plugin check` from it and show it in the dropdown. Admin class will be added in the https://github.com/10up/plugin-check/issues/32

## Tests Coverage

- Verify the dropdown plugin list with the actual plugin list.
- Verify the dropdown template's markup with the actual markup we expected.

**Comment by vishalkakadiya** [comment]
@jjgrainger updated this epic. Can you review this before sending it to Felix? Thank you!

**Comment by jjgrainger** [comment]
Thanks @vishalkakadiya 

See my comment on https://github.com/10up/plugin-check/issues/32#issuecomment-1403417117.

I think we should combine this issue with #32 and close this one.

**Comment by vishalkakadiya** [comment]
@jjgrainger I have added the details on #32, so we can close this now. Thank you!

**Comment by felixarntz** [comment]
Closing this as it is now covered in #32, to avoid confusion.
