### ISSUE TITLE
Plugin Check plugin will remove code in .htaccess

### ISSUE THREAD

**Issue by codestylist** [10up/plugin-check#330]
When I run the Plugin Check plugin on any plugin, the entire part in the `.htaccess` file between `#BEGIN WordPress` and `#END WordPress` is removed.
I mean the code from `<IfModule>` to `</IfModule>`.
I need to open the Settings > Permalinks page, which regenerates the missing rows.

Edit: This happen when the permalink structure is set to "Post name"

**Comment by swissspidy** [comment]
That sounds very surprising 🤔 Is this with version 0.2.1 from WordPress.org or the new version from this repository? You might want to check out the latter in case you haven't. It's possible that this issue simply no longer exists.

**Comment by codestylist** [comment]
Thank you @swissspidy for your reply. I use the latest version from github and the last update was the 27th of November. It shows "Version n.e.x.t". Unfortunately the problems still exist.
Is there anything I can do to provide more data so you can reproduce the issue?

**Comment by swissspidy** [comment]
Maybe it only happened for a specific plugin that you tested? Does it still happen with e.g. Hello Dolly?

Here's what I tried right now using the same version from GitHub:

1. Clear `.htaccess` file and go to Settings -> Permalinks to verify that WordPress successfully adds rewrite rules again, proving that the file is used and everything works as expected.
2. Go to Tools -> Plugin Check, select all categories and run Plugin Check against plugins such as Hello Dolly and Performant Translations
3. The `.htaccess` still contained all rewrite rules and pretty permalinks still work just fine on the site. Nothing got deleted.

As you can see, I am unable to reproduce this with these steps. Maybe someone else has better luck.

**Comment by mukeshpanchal27** [comment]
@swissspidy, I encountered the same issue when running checks against the activated plugin. Perhaps there is an issue with the runtime checks?

**Comment by swissspidy** [comment]
Ahh, you're running checks against an already active plugin 💡 

This way I can indeed reproduce the issue. The `.htaccess` file looks like this afterwards:

```

# BEGIN WordPress
# The directives (lines) between "BEGIN WordPress" and "END WordPress" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.

# END WordPress
```

@mukeshpanchal27 Wanna look into this? I'm not familiar with how runtime checks set up things.

**Comment by codestylist** [comment]
Thank you @swissspidy @mukeshpanchal27 . I have verified this and can confirm that the issue occurs only when I run a test of an activated plugin.
