### ISSUE TITLE
AJAX error when only Accessibility is checked

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#342]
When only Accessibility is checked, AJAX error halts the check.

## Steps to reproduce

* Install `Breadcrumb NavXT` plugin
* In the admin panel, go to `Tools` -> `Plugin Check`
* Select `Breadcrumb NavXT` from the dropdown
* Check only `Accessibility`
* Click `Check it!`

## Output

In the console:
<img width="597" alt="Screen Shot 2023-12-17 at 1 05 28 PM" src="https://github.com/WordPress/plugin-check/assets/2098823/b2eca215-1f3a-4fb4-91d2-44398bbd9cf5">

This is the error in `debug.log` file:

```
[17-Dec-2023 07:22:25 UTC] PHP Fatal error:  Uncaught TypeError: WordPress\Plugin_Check\Checker\Abstract_Check_Runner::set_check_slugs(): Argument #1 ($check_slugs) must be of type array, null given, called in /var/www/html/wp-content/plugins/plugin-check/includes/Admin/Admin_AJAX.php on line 115 and defined in /var/www/html/wp-content/plugins/plugin-check/includes/Checker/Abstract_Check_Runner.php:168
Stack trace:
#0 /var/www/html/wp-content/plugins/plugin-check/includes/Admin/Admin_AJAX.php(115): WordPress\Plugin_Check\Checker\Abstract_Check_Runner->set_check_slugs(NULL)
#1 /var/www/html/wp-includes/class-wp-hook.php(324): WordPress\Plugin_Check\Admin\Admin_AJAX->set_up_environment('')
#2 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#3 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /var/www/html/wp-admin/admin-ajax.php(188): do_action('wp_ajax_plugin_...')
#5 {main}
  thrown in /var/www/html/wp-content/plugins/plugin-check/includes/Checker/Abstract_Check_Runner.php on line 168

```

**Comment by ernilambar** [comment]
After some digging I found out that this error is coming because there are no Checks under `Accessibility` category. So `$checks` variable became `null` but we require that variable as `array`. So it generated PHP fatal error.

**Comment by mukeshpanchal27** [comment]
Thanks @ernilambar for raising. I also reproduce same error. Assign to my self.
