### ISSUE TITLE
Notice: undefined index

### ISSUE THREAD

**Issue by yakacj** [10up/plugin-check#349]
Hello, 

I getting admin notice from Plugin Check ( PCP) version 0.2.2 : Notice: Undefined index: argv in …/plugins/plugin-check/inc/class-phpcs-runner.php on line 126.

$_SERVER[‘argv’]; I replaced with isset( $_SERVER[‘argv’] ) ? $_SERVER[‘argv’] : ”;

Now ok.

**Comment by mukeshpanchal27** [comment]
Thank you for bringing up the concern. This issue has already been addressed and fixed, as reported in #338, with an associated PR #340. These changes are set to be included in the upcoming release.

cc. @bordoni
