### ISSUE TITLE
Allow HTML tags in error/warning messages

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#355]
Followup from https://github.com/WordPress/plugin-check/issues/312

Currently we dont allow HTML tags in messages.

Opinions:

> Using late escaping principles, it would make sense to me that if HTML is being stored in messages that each output target would be responsible for its own escaping, so we could use `wp_kses` to define the subset of HTML that is supported in the admin, while CLI strips all tags.

_Originally posted by @joemcgill in https://github.com/WordPress/plugin-check/issues/312#issuecomment-1864730259_

> I like the idea of using `wp_kses()` instead of `esc_html()`:
> * For regular UI output, support a few basic inline tags (e.g. `a[href]`, `strong`, `em`, `code`, ...)
> * For CLI, support none, effectively the same as stripping tags (i.e. we probably would just use [`wp_strip_all_tags()`](https://developer.wordpress.org/reference/functions/wp_strip_all_tags/)

_Originally posted by @felixarntz in https://github.com/WordPress/plugin-check/issues/312#issuecomment-1864803007_

We need to finalize the Acceptance Criteria including list of tags those should be allowed.

**Comment by swissspidy** [comment]
Are there actually any messages right now with HTML in them?

**Comment by ernilambar** [comment]
I think `<code>` was replaced by `"` in those trademark check. This improvement is for safeguarding results which are generated by other WPCS rules which we don't control. Or results from checks from other addons.
