### ISSUE TITLE
 Fatal error when in checks in `--checks` and `--exclude-checks` overlaps

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#359]
Eg:
`wp plugin check hello-dolly --checks=plugin_review_phpcs,late_escaping --exclude-checks=late_escaping`

Our CLI arguments:

    [--exclude-checks=<checks>]
    Exclude checks provided as an argument in comma-separated values, e.g. i18n_usage, late_escaping. Applies after evaluating `--checks.`

Since we are calculating excludes after checks, overlapping of checks in the arguments should not generate fatal error.
In the above example scenario, only `plugin_review_phpcs` should be in the final checks list.

**OR**
If we do not expect both arguments in the same command, we should validate and give `WP_CLI::error()`

Output: 
<img width="1097" alt="Screenshot 2024-01-10 at 12 17 28 PM" src="https://github.com/WordPress/plugin-check/assets/2098823/19d6edd5-1af4-4a9e-8a30-8b529a5135af">

**Comment by ernilambar** [comment]
cc: @swissspidy @felixarntz @mukeshpanchal27

**Comment by swissspidy** [comment]
Let‘s fix the fatal error

**Comment by felixarntz** [comment]
@ernilambar Good catch!

I'd be okay with either approach for the fix, though I slightly prefer to fail with an error if the same check is used in both `--checks` and `--exclude-checks` (since that wouldn't make any sense anyway).

**Comment by ernilambar** [comment]
@felixarntz This fatal error is triggered in the very beginning while setting up runner. So I am not sure that it is possible to validate checks inside `check()` command and show WP_CLI error there.

**Comment by ernilambar** [comment]
Related to https://github.com/WordPress/plugin-check/issues/348
