### ISSUE TITLE
Enhancement: Add option to exclude files from checking

### ISSUE THREAD

**Issue by mukeshpanchal27** [10up/plugin-check#388]
**Feature Description**

In #206, we introduced the ability to run checks for specific categories in both WP Admin and WP-CLI. However, one important aspect was missing - the ability to exclude specific files from all checks. This proposed enhancement aims to provide users with the flexibility to exclude certain files they don't wish to update, enhancing the overall usability, especially in the CLI.

#### Proposed Implementation:

**For WP-CLI:**

- Introduce a new optional parameter `--exclude-files` for the CLI.
- The `--exclude-files` parameter should expect a comma-separated list of files.
- When this parameter is provided, the specified files should be excluded from the check results.

**For WP Admin:**

- Implement a user interface similar to the provided design (see attached screenshot).
- Users should be able to specify files for exclusion through the UI.

#### Designs:

For WP-CLI:
```
wp plugin check --exclude-files=file1,file2,file3
```

For WP Admin:
![WP Admin Design](https://github.com/WordPress/plugin-check/assets/10103365/646aa94d-da3d-490c-9133-162b53f1e542)

#### Benefits:

- Improved flexibility for users by allowing them to exclude specific files from checks.
- Enhances the WP-CLI experience with the addition of the `--exclude-files` parameter.

**Comment by mukeshpanchal27** [comment]
cc. @felixarntz @joemcgill @eclarke1

**Comment by ernilambar** [comment]
I think we should keep that textarea (and another textarea for excluding directories which is not implemented yet) should be display under a toggler. Otherwise lots of screen area would be occupied by form only. Eg:

![Screenshot 2024-01-12 at 10 54 12 AM](https://github.com/WordPress/plugin-check/assets/2098823/735bcfdb-a47f-43f4-9f36-13a0c9de1673)

**Comment by mukeshpanchal27** [comment]
> I think we should keep that textarea (and another textarea for excluding directories which is not implemented yet) should be display under a toggler. Otherwise lots of screen area would be occupied by form only. Eg:

+1. I would like to get other folks( Felix, @swissspidy ) feedback on this before move forward.

**Comment by felixarntz** [comment]
@mukeshpanchal27 I would prefer if we only implemented this for WP-CLI for now. For CLI commands, having a lot of flexibility is good, but for UI it's a different beast - last but not least we should keep in mind "Decisions not options".

I'm not saying we definitely shouldn't implement this in the UI, but it's a lot more of a detail and I think it would need more careful design consideration than just adding another checkbox. The UI we have right now is super rudimentary, and I don't think adding more and more on top of it is a good idea. I'd prefer to stick with the essentials based on where we are now.

**Comment by swissspidy** [comment]
Closing for now as there is the WP-CLI integration.
