### ISSUE TITLE
Create Demo_Posts_Creation_Preparation

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#40]
## Description

Demo post creation preparation will ensure that the plugin being checked is provided with all the necessary posts it needs to conduct the audit.

## Acceptance Criteria

- Class `Demo_Posts_Creation_Preparation` should be created and exists at `includes/Checker/Preparations`
- Class `Demo_Posts_Creation_Preparation` should extend `Preparation` interface
- Class `Demo_Posts_Creation_Preparation` has a constructor.
    - The constructor accepts a `$posts` parameter
    - The `$posts` parameter passed will be an array of posts data. Each item in the array will contain post data compatible with the [`wp_insert_post()`](https://developer.wordpress.org/reference/functions/wp_insert_post/) function.
    - The post data passed will be assigned to a protected property to be used later.
- `prepare()` must be implemented from `Preparation` interface
    - The method will loop over the post data array passed in the constructor and create each post using the `wp_insert_post()` function.
    - For each post successfully created, the post ID returned will be stored in an array.
    - The cleanup function returned will loop over the array of post IDs created and remove each post from the database.

## Tests Coverage

- `Demo_Posts_Creation_Preparation` instance expected to be implementing of `Preparation` interface
- `prepare()` method adds the passed posts to the database.
- The cleanup function returned by `prepare()` removes the posts from the database.

**Comment by felixarntz** [comment]
@jjgrainger Which purpose would those posts serve, or rather which checks for example would that be used for? Which posts does this preparation need to create? I think the ACs here will require a lot more detail, as they are quite vague and it is unclear what this `Preparation` should do. ACs need to be precise to leave no room for interpretation, except for technical details. They state "required demo posts", but that doesn't really mean anything - required for what? :)

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

I've not had a chance to review these AC's in detail but my initial thoughts are that we would need at least one demo post for each publicly available post type.

These would be required for checks such as #24 where the Check will simulate loading different URLs. We would want to ensure there is content for public post types that a plugin may create (e.g Products).

Therefore, this preparation would loop over all public post types registered and create a post for each post type.

**Comment by felixarntz** [comment]
@jjgrainger That approach makes sense to me as a starting point. Let's iterate on the ACs here once we've clarified the infrastructure ACs.

**Comment by jjgrainger** [comment]
Thanks @felixarntz I agree. It makes sense to revisit this when it applies to a concrete check. Then this issue can be tackled alongside that check to make it easier for testing.

**Comment by felixarntz** [comment]
@jjgrainger ACs LGTM!
