### ISSUE TITLE
Update Readme check to include missing plugin header

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#402]
Related: https://github.com/WordPress/plugin-check/issues/198

In current readme validator, warnings are raised if following fields are missing:

- Tested up to
- Stable tag
- Contributors

We could also implement here in trunk a similar parity with the current readme validator.

Ref:

![Screenshot 2024-01-25 at 4 08 59 PM](https://github.com/WordPress/plugin-check/assets/2098823/0736aab4-84e2-4082-aa95-4137d7b1e2af)

**Comment by ernilambar** [comment]
* Stable Tag - Since we already have special method for Stable Tag checking, I have added `no_stable_tag` in that same function. Related PR - https://github.com/WordPress/plugin-check/pull/403

**Comment by swissspidy** [comment]
#414 seems fine at first glance, but I recommend asking the plugin review team whether it's useful for them

**Comment by ernilambar** [comment]
@foosantos We have already implemented missing Stable Tag. Would it be helpful if we also implement missing `Tested up to` and `Contributors`? By default `contributor_ignored` warning is ignored, so missing `Contributors` won't be warned.

**Comment by felipevelzani** [comment]
cc @bordoni

**Comment by davidperezgar** [comment]
Yes, we have to check that the plugin has a correct readme.

**Comment by ernilambar** [comment]
Fixed in https://github.com/WordPress/plugin-check/pull/414
