### ISSUE TITLE
Trunk version not available on Subversion

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#432]
Ref: https://translate.wordpress.org/projects/wp-plugins/plugin-check/

Why strings are not showing in **Development**? Any idea?

**Comment by swissspidy** [comment]
Because the development version, i.e. trunk, currently only contains the readme and no code.

cc @bordoni

**Comment by bordoni** [comment]
Ohh I see, good point. But the code under `trunk` would be the same as the `Stable Tag:`. I am not sure how we would benefit from having that. 

I know there are other benefits from having `trunk`.

**Comment by ernilambar** [comment]
I noticed this issue when translating. I use this plugin https://wordpress.org/plugins/force-update-translations/ But due to some issue, this plugin only downloads strings from Development.

**Comment by swissspidy** [comment]
In theory you could actually put a beta or release candidate in `trunk` but I don't think we need that.

It's pretty normal for trunk + latest tag to be identical. It would also make it easier to use `https://downloads.wordpress.org/plugin/plugin-check.zip` for downloading the latest release.

_Not_ using `trunk` is more confusing than useful.

**Comment by dd32** [comment]
> It's pretty normal for trunk + latest tag to be identical.

Yeah; Either have trunk+tag the same, or have trunk actually have the code from GitHub trunk sync'd daily/every push.

If the `deploy` workflow is used; it should set trunk contents to that of the stable release. I've just fixed the secrets/svn credentials for this repo.

> It would also make it easier to use https://downloads.wordpress.org/plugin/plugin-check.zip for downloading the latest release.

for that, use https://downloads.wordpress.org/plugin/plugin-check.latest-stable.zip

**Comment by swissspidy** [comment]
> > It's pretty normal for trunk + latest tag to be identical.
> 
> Yeah; Either have trunk+tag the same, or have trunk actually have the code from GitHub trunk sync'd daily/every push.
> 
> If the `deploy` workflow is used; it should set trunk contents to that of the stable release.

Correct. And we intended to use that workflow. But the initial 1.0.0 and 1.0.1 were pushed manually because the action timed out due to the many new files being added.

So right now the empty trunk folder prevents us from using this workflow.

So my **tl;dr** is: let's just fix this please to make our lives easier :)

>  I've just fixed the secrets/svn credentials for this repo.

Can you clarify this? The GitHub secrets in this repo should have been correct already (using the [performanceteam](https://profiles.wordpress.org/performanceteam/) user). What did you change these to now?

> > It would also make it easier to use [downloads.wordpress.org/plugin/plugin-check.zip](https://downloads.wordpress.org/plugin/plugin-check.zip) for downloading the latest release.
> 
> for that, use [downloads.wordpress.org/plugin/plugin-check.latest-stable.zip](https://downloads.wordpress.org/plugin/plugin-check.latest-stable.zip)

TIL! Thanks.

**Comment by swissspidy** [comment]
The code is now in `trunk`
