### ISSUE TITLE
Make the Plugin Check GitHub Action official

### ISSUE THREAD

**Issue by swissspidy** [10up/plugin-check#444]
https://github.com/swissspidy/wp-plugin-check-action is a very convenient way for people to get up and running with Plugin Check.

We should further refine it and make it "official" by moving it to the WordPress GitHub organization.

**Comment by felixarntz** [comment]
@swissspidy Which refinements would be needed for the action to be in a good MVP state? Or is it already and we can propose moving it?

I wonder what's our "to do" list here :)

**Comment by swissspidy** [comment]
It's pretty stable but there are some [open issues](https://github.com/swissspidy/wp-plugin-check-action/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) that are relevant.

**Comment by swissspidy** [comment]
@desrosj Is this perhaps something you could help with?

I don't have rights to transfer https://github.com/swissspidy/wp-plugin-check-action to the WordPress organization.

Ideally the repo would live at `https://github.com/WordPress/plugin-check-action`

I would make you an admin on the repo first so that you could initiate the transfer. Or I can maybe start the transfer and you just have to approve it.

**Comment by desrosj** [comment]
@swissspidy Sure, let's coordinate in Slack and get this transferred over.

**Comment by swissspidy** [comment]
Success! https://github.com/WordPress/plugin-check-action/
