### ISSUE TITLE
Add to plugin developer handbook

### ISSUE THREAD

**Issue by swissspidy** [10up/plugin-check#445]
PCP should be listed in the plugin developer handbook, for example on https://developer.wordpress.org/plugins/developer-tools/.

Who owns that documentation and can help getting PCP on there?

Aside: Debug Bar probably shouldn't be featured so prominently, most of the add-ons haven't been updated for many years.

**Comment by bordoni** [comment]
I can take ownership on this one, very good catch. I will bring up on the Plugin Review team to make sure we are all on the same page but I will make the changes and close the issue once we get there.

Any suggestions on copy that we should have? I will switch away from Debug bar to recommend Query Monitor and other tools like that.

**Comment by swissspidy** [comment]
Awesome, thanks!

I think as a starting point we can reuse parts of the [plugin description](https://wordpress.org/plugins/plugin-check/). I'd emphasize the fact that it's useful even _after_ initial submission.

In the future we could also link to the GitHub Action ( see#444 and #442) we built as an easy way for developers to get started with ongoing checks.

**Comment by davidperezgar** [comment]
I add @frantorres that has made changes utimately to the handbook .

**Comment by davidperezgar** [comment]
I've added a [PR](https://github.com/WordPress/developer-plugins-handbook/pull/15) in order to make it possible.

**Comment by frantorres** [comment]
It is now mentioned here: https://developer.wordpress.org/plugins/developer-tools/helper-plugins/

**Comment by davidperezgar** [comment]
Thanks @frantorres !
