### ISSUE TITLE
Blog post(s) to spread the word about Plugin Check

### ISSUE THREAD

**Issue by swissspidy** [10up/plugin-check#446]
PCP V1 has been published rather quietly. I think there's lots of room for improvement to further spread the word about PCP.

For example:

* Once Plugin Check is fully integrated into the plugin submission process, publish a blog post on make/plugins.
* Once the GitHub action is moved to the WordPress GitHub org (#444), publish a blog post on https://developer.wordpress.org/news.

**Comment by felixarntz** [comment]
@swissspidy Maybe we can prioritize #444 so that we could already reference the GitHub Action in the eventual Make Plugins post as well, alongside the plugin integrated into the submission process?

**Comment by davidperezgar** [comment]
Definitely we have to work on this.

**Comment by swissspidy** [comment]
Started a draft here:
https://docs.google.com/document/d/1l1RRf82mny1CyghyCa-VUqQJ714y27esJOSXs6oeGbQ/edit?usp=sharing

**Comment by swissspidy** [comment]
Blog post can be published next Monday ✅

**Comment by davidperezgar** [comment]
Yeah!
