### ISSUE TITLE
possible false positive

### ISSUE THREAD

**Issue by Markmcl** [10up/plugin-check#450]
I use the plugin to check new plugins before usage.
Could you please read this https://wordpress.org/support/topic/plugin-check-errors-2/#post-17546611
thread for details of a possible case of a false positive.
Thanks for the plugin and your work.

**Comment by swissspidy** [comment]
Hi there

What exactly is your question? As you already stated on the thread, there can be false positives, and we are working toward minimizing such cases and providing documentation to make better informed decisions.

Looking at this particular plugin a bit, I would say some of those reported errors may be false positives, some others definitely need improvement, at least in my eyes.
