### ISSUE TITLE
BuddyPress: issues with custom CLI commands, false positive?!

### ISSUE THREAD

**Issue by renatonascalves** [10up/plugin-check#463]
I think I found an _odd_ behavior, and I'd like to clarify if this is expected behavior. I run the plugin with the BuddyPress plugin, and our custom CLI commands (which are bundled with BuddyPress core) are on the list of issues:

![CleanShot 2024-05-03 at 23 20 55@2x](https://github.com/WordPress/plugin-check/assets/19148962/fd615e5d-d8ce-42d3-9f05-684fc9543e2b)

I'd argue that the only people that can run CLI commands are folks with access to the server, so escaping issues would be the least of one’s concern by then. Also, those commands are not user-facing.

Similarly, WP core doesn't escape similar commands. See [here](https://github.com/search?q=org%3Awp-cli+if+%28+%27ids%27+%3D%3D%3D+%24formatter-%3Eformat+%29+%7B&type=code).

**Comment by renatonascalves** [comment]
Maybe this plugin should try to identify if the plugin is using custom CLI commands and not report false positive _issues_ for those files. Since it uses a [different WPCS ruleset](https://github.com/wp-cli/wp-cli-tests).

**Comment by renatonascalves** [comment]
Just a note that those _issues_ were already fixed in our custom commands: https://github.com/buddypress/wp-cli-buddypress/releases/tag/3.0.0 But we have not released it yet.

**Comment by swissspidy** [comment]
Heya, yeah those are false positives.

It's impossible for a static analysis tool like PHPCS to reliably detect such use cases, so I'd suggest simply ignoring such false positives.

**Comment by renatonascalves** [comment]
Sounds good. Those _issues_ were resolved in v3 of our API. So I'll resolve this issue.
