### ISSUE TITLE
Allow `wp-` prefixes on plugins

### ISSUE THREAD

**Issue by dd32** [10up/plugin-check#464]
Per https://meta.trac.wordpress.org/ticket/5868 Using `WP ...` as the plugin name is allowed, but the trademark checks on WordPress.org block it preemptively.

Prefixes such as `"WP .."` and `"WC ..."` should not show as prohibited, but rather, note that they cannot be changed later to the trademarked term.

Plugin check may want to simply remove the `wp-` trademark check, leaving that to w.org/plugins, or may want to add a lesser-level note that it can't be changed to the trademark.

**Comment by davidperezgar** [comment]
I'd say to use a warning for that.
