### ISSUE TITLE
Getting error "The plugin readme.txt does not exist."

### ISSUE THREAD

**Issue by ajeetku** [10up/plugin-check#465]
Have readme.txt in root of plugin with readme.md.
but still getting error "The plugin readme.txt does not exist."
for more information of system

``
### wp-core ###

version: 6.5.3
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /index.php/%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: C:\xampp\htdocs\wordpress
wordpress_size: 54.68 MB (57339081 bytes)
uploads_path: C:\xampp\htdocs\wordpress/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: C:\xampp\htdocs\wordpress/wp-content/themes
themes_size: 12.12 MB (12706752 bytes)
plugins_path: C:\xampp\htdocs\wordpress/wp-content/plugins
plugins_size: 7.46 MB (7821697 bytes)
database_size: 2.19 MB (2293760 bytes)
total_size: 76.45 MB (80161290 bytes)

### wp-active-theme ###

name: Twenty Twenty-Four (twentytwentyfour)
version: 1.1
author: the WordPress team
author_website: https://wordpress.org
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, widgets-block-editor, block-templates
theme_path: C:\xampp\htdocs\wordpress/wp-content/themes/twentytwentyfour
auto_update: Disabled

### wp-themes-inactive (2) ###

Twenty Twenty-Three: version: 1.4, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.7, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (2) ###

XXXXXXXXXXX: version: 1.0.0, author: XXXX, Auto-updates disabled
Plugin Check (PCP): version: 1.0.1, author: WordPress Performance Team and Plugin Review Team, Auto-updates disabled

### wp-plugins-inactive (2) ###

Akismet Anti-spam: Spam Protection: version: 5.3.2, author: Automattic - Anti-spam Team, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: 1
post_max_size: 400M
upload_max_filesize: 400M
max_effective_size: 400 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.58 (Win64) OpenSSL/3.1.3 PHP/8.2.12
php_version: 8.2.12 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 120
memory_limit: 512M
max_input_time: 60
upload_max_filesize: 400M
php_post_max_size: 400M
curl_version: 8.4.0 OpenSSL/3.1.3
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false
current: 2024-06-02T02:42:35+00:00
utc-time: Sunday, 02-Jun-24 02:42:35 UTC
server-time: 2024-06-02T02:42:29+00:00

### wp-database ###

extension: mysqli
server_version: 10.4.32-MariaDB
client_version: mysqlnd 8.2.12
max_allowed_packet: 1048576
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: C:\xampp\htdocs\wordpress/wp-content
WP_PLUGIN_DIR: C:\xampp\htdocs\wordpress/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

``

**Comment by swissspidy** [comment]
Hi there, thanks for your report!

The Site Health information is not as important as the information about the plugin you were testing.

I also see you're on Windows, so it might be a simple Windows issue. Are you perhaps able to try it on another machine?

**Comment by ernilambar** [comment]
I guess this is fixed in https://github.com/WordPress/plugin-check/pull/453

PR has been merged but it is not released in directory.
