### ISSUE TITLE
Calling ReflectionProperty::setValue() with a single argument is deprecated (PHP 8.3)

### ISSUE THREAD

**Issue by ipajen** [10up/plugin-check#471]
### Description
`PHP Deprecated:  Calling ReflectionProperty::setValue() with a single argument is deprecated in /xx/public_html/blog/wp-content/plugins/plugin-check/includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php on line 201`

 [deprecated in PHP 8.3 link](https://www.php.net/manual/en/reflectionproperty.setvalue.php)

### Environment
- WordPress: 6.6-beta2
- PHP: 8.3.7
- Server: LiteSpeed
- Database: mysqli (Server: 10.6.18-MariaDB / Client: mysqlnd 8.3.7)
- Browser: Edge 125.0.0.0 (Windows 10/11)
- Theme: Twenty Twenty-Four 1.1
- MU-Plugins: 
  * block-automation-by-installatron.php 
  * Health Check Troubleshooting Mode 1.9.0
- Plugins: 
  * Core Rollback 1.3.5
  * Enable jQuery Migrate Helper 1.4.0
  * Health Check & Troubleshooting 1.7.0
  * Optimization Detective 0.3.1
  * Plugin Check (PCP) 1.0.1
  * Query Monitor 3.16.3
  * WordPress Beta Tester 3.5.5
  * WPVulnerability 3.2.0

**Comment by mukeshpanchal27** [comment]
Already fixed in trunk with issue #458, It will shipped in upcoming version.
