### ISSUE TITLE
Allow static checks to be run against an arbitrary path

### ISSUE THREAD

**Issue by joemcgill** [10up/plugin-check#478]
Currently the WP CLI command is limited to only run checks against plugins that are installed on the same site as Plugin Check. 

This is because it eventually calls the `Plugin_Request_Utility::get_plugin_basename_from_input()` method during the setup process which throws an Exception if the plugin is not installed.

To satisfy the requirements of https://github.com/WordPress/plugin-check/issues/441#issuecomment-2190961036, we need to be able to run checks against a plugin that is located outside the WordPress filesystem, e.g. `/tmp`.

Ideally, this would work by passing a CLI command like:

```
wp plugin check /tmp/plugin-path
```

When the path is not to an active plugin, only static checks should be eligible to be run.

**Comment by swissspidy** [comment]
Related:

* #153

**Comment by davidperezgar** [comment]
Yes! It's necessary for the form submission.

**Comment by davidperezgar** [comment]
I've commited first approach how to use in an arbitrary path. It's working. Only rename variables would need it.
