### ISSUE TITLE
Check: Tested up to Latest version of WordPress

### ISSUE THREAD

**Issue by davidperezgar** [10up/plugin-check#481]
I would add to check the actual version of WordPress. It must be Tested up "actual version".

In order to have always the latest version, I've [asked to meta](https://wordpress.slack.com/archives/C02QB8GMM/p1719654997418999), and we have some methods to check that:

> Yes, use one of these:
> https://api.wordpress.org/core/stable-check/1.0/
> 3rd line of https://api.wordpress.org/core/version-check/1.1/
> Or just json decode https://api.wordpress.org/core/version-check/1.7/
> So finally we have a complete check.

The error that we show to the users is something like this ERROR: Tested up to: 6.4 < 6.5

And we don't compare with minor version, just major.

It should have a transient with expired date 1 day.

Description for this issue:

> ## Tested Up To Value is Out of Date, Invalid, or Missing
> 
> The tested up to value in your plugin is not set to the current version of WordPress. This means your plugin will not show up in searches, as we require plugins to be compatible and documented as tested up to the most recent version of WordPress.
> 
> Please update your readme to show that it is tested up to the most recent stable major version of WordPress. For example if WordPress said that version 99.0.1 was the current release, you would be able to set your value to 99.0 or 99.0.1, as 99.0.1 would be considered a minor release.
> 
> The following links will assist you in understanding WordPress's versioning and the latest version:
> 
> https://wordpress.org/download/
> https://make.wordpress.org/core/handbook/about/release-cycle/version-numbering/
> 
> You cannot set it beyond the current version, as that will cause your plugin not to be available on searches. Also remember that WordPress has made late changes in releases, so claiming compatibility with an incomplete version is likely to land you in trouble.
> 
> From your readme file:
> 
> ERROR: Tested up to: 6.4 < 6.5

**Comment by ernilambar** [comment]
I am working on this.
