### ISSUE TITLE
Default selected check category could be customizable using filter

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#494]
Currently default selected category is set to `plugin_repo`. It would be great if we could provide filter for that so that I can assign my custom category/categories as default.

```
$user_enabled_categories = get_user_setting( 'plugin_check_category_preferences', 'plugin_repo' );
```

**Comment by davidperezgar** [comment]
Yes, why not?

**Comment by davidperezgar** [comment]
> I am not being able to register my own custom check categories in which I want to register my custom checks.
> 
> Currently categories are hardcoded.
> 
> public static function get_categories() {
> 	return array(
> 		self::CATEGORY_GENERAL,
> 		self::CATEGORY_PLUGIN_REPO,
> 		self::CATEGORY_SECURITY,
> 		self::CATEGORY_PERFORMANCE,
> 		self::CATEGORY_ACCESSIBILITY,
> 	);
> }

**Comment by ernilambar** [comment]
https://github.com/WordPress/plugin-check/pull/508 and https://github.com/WordPress/plugin-check/pull/509 should fix this issue.
