### ISSUE TITLE
Trademarks check fails should show as a warning

### ISSUE THREAD

**Issue by davidperezgar** [10up/plugin-check#495]
The plan for this plugin is to be in the submission form, and I cannot block uploads for example from WooCommerce. They actually upload plugins and if it marks the use of the trademark as error, will block the plugin upload.

If they get ERROR, it won't make a PASS, so we should change as a WARNING, and the plugin team can check manually the Plugin name.

**Comment by frantorres** [comment]
Just to give context, today the submission form blocks submissions for certain-common slug beginnings (including some common trademarks).
https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/plugin-directory/shortcodes/class-upload-handler.php#L613
In case some of this common trademarks wants to submit a plugin, they ask the plugin team for help to bypass that limitation.
