### ISSUE TITLE
Hide "View in code editor" link for uneditable files

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#515]
Errors like `hidden_files`, `application_detected`, `no_plugin_readme`, etc should not have **View in code editor** link as those files are not editable. Clicking on those links are now just going to error page.

Example:

<img width="1113" alt="Screenshot 2024-07-09 at 11 01 46 AM" src="https://github.com/WordPress/plugin-check/assets/2098823/dbc9855b-7915-403d-b25f-4518e376c228">

**Comment by swissspidy** [comment]
Is there a function in WP to determine whether a file can be edited or not? Then we can just reuse that.
