### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by webguyio** [10up/plugin-check#516]

**Comment by ernilambar** [comment]
@bhadaway Can you please share what errors you are getting?

**Comment by bhadaway** [comment]
Sorry, I'm not referring to errors with Plugin Check itself, but rather the errors it's able to sniff out in the plugins it's scanning. There seems to be something missing that's limiting Plugin Check in my testing environment. It's LAMP, but I suspect there are some specific PHP mods that the plugin relies on to fully function?

**Comment by swissspidy** [comment]
Can you please share the plugin you‘re testing and some examples of the differences you‘re seeing?

**Comment by bhadaway** [comment]
Sure, let's use https://wordpress.org/plugins/stop-spammer-registrations-plugin/ as an example.

Testing in my test environment, it only is able to find like 3 issues, and those are only basic issues about the readme and license.

Using https://playground.wordpress.net/, it is actually able to scan all the code and find hundreds of issues.

If there aren't any special PHP mods that need to be enabled, perhaps there are known server or WordPress security settings that can interfere with Plugin Check?

**Comment by swissspidy** [comment]
No there aren't any special requirements or known incompatibilities.

With the latest version of Plugin Check (1.0.2 at the time of writing) and all checkboxes ticked, I get hundreds of errors for that plugin.

If you don't get the same results, try disabling all other plugins and share your Site Health information so we can try to help debug the issue.

**Comment by bhadaway** [comment]
Okay, I'll spend more time debugging and if I ever figure it out, I'll report back. Thanks.

**Comment by swissspidy** [comment]
Sounds good 👍  In the meantime I'm closing this, but if you find anything we can reopen.
