### ISSUE TITLE
Move Security Checks to Plugin REPO category and folder

### ISSUE THREAD

**Issue by davidperezgar** [10up/plugin-check#538]
Plugin Repo checks are mainly focused in security.
What we do is check the security issues and some more checks. So, I'd propose to move all security checks to plugin repo.

Another reason for this, it's the category checked by default and it will be in the submission form, so we need these security checks to be in Plugin repo category.

We can explain in the description plugin the focus of all checks in plugin repo.

**Comment by joemcgill** [comment]
Individual checks can apply to multiple categories at the same time, so perhaps organizing the folders only by category isn't the best organization structure?

As I see it, the Plugin Repo category serves as a collection of checks from several categories. For example, when running checks marked with the "plugin repo" category, you might run checks that include a subset of the following:

* General (best practices) – Does the plugin header include the correct information, etc.
* Security – Is the plugin doing something insecure that we don't want to allow in the plugin repo

Similarly, if you were only running security checks, you would want to ensure that the ones that are required for submission to the plugin repo are not excluded.

**Comment by swissspidy** [comment]
FWIW the folder organization is mostly for code ownership

**Comment by davidperezgar** [comment]
Ok nice then. I wasn't sure about this. Thanks for clarification.
