### ISSUE TITLE
AddToAny floating share button doesn't appear after reactivating plugin

### ISSUE THREAD

**Issue by 4syllabus** [10up/plugin-check#556]
Hi
I deactivated addtoany plugin and when reactivated, floating share button disappeared on my blog [https://4syllabus.in/](https://4syllabus.in/) . what cause the issue, please help.

**Comment by swissspidy** [comment]
Hi there

For issues with the AddToAny plugin you'll need to ask in their support forums. See https://wordpress.org/support/plugin/add-to-any/

This repository is for another plugin that has nothing to do with AddToAny.
