### ISSUE TITLE
Create HTML report

### ISSUE THREAD

**Issue by davidperezgar** [10up/plugin-check#558]
We need in the Plugin Review Team a report in HTML so we can share with the user and it should be grouped by results and then files. 

I think that this report could be used for other users to share the problem to developers, so it could be helpful. And even, we could make a button to send to any email. 

So when checks are executed, it could give you a button to send to a email, and other button to copy to clipboard.

**Comment by davidperezgar** [comment]
I have some doubts about this PR. It's necessary but how can we do it?
1- Should we save the reports in a temporary folder that is always accessible? 
2- We should protect that folder for SEO and would it be accessible without an user? so someone could share that report?
3- Should we make an interface where we can see historic reports?
4- Would it be necessary to send it by email?

As I understand this report it's not only needed for the team, It can be a tool for developers and can share problems in the plugin.

**Comment by ernilambar** [comment]
1. We could save reports under uploads folder, may be under `plugin-check-reports`. Filename could be `report-plugin-slug.html` or similar.
2. We should absolutely protect folder from unauthorized access.
3. May be reports interface could be developed as a separate addon.
4. Same as point 3.

**Comment by swissspidy** [comment]
IMHO this might be best as a separate plugin, maybe one specifically living on dotorg, which I presume already has infrastructure for sending emails etc.

That plugin could simply run the PCP WP-CLI command and then format the results in HTML, and then you could do whatever you want with that (copy the HTML, save it to a file, send via email, etc.)

But I don't see how this functionality in PCP itself right now.

**Comment by davidperezgar** [comment]
I see it as you can share the reports. I see very practical as you can share. For Example, I saw recently that QIT from WooCommerce is based on that. 

This is something that we could use it in our internal plugin, but I see very practical for users. They could share to the developers the report and we can spread better the use of this plugin to more people.

**Comment by swissspidy** [comment]
I see PCP more as a developer tool, not a tool end users use to send error reports to developers.

**Comment by davidperezgar** [comment]
We are going to move to our internal Addon and see in the future if it's useful for developers.
