### ISSUE TITLE
The plugin readme.txt does not exist.

### ISSUE THREAD

**Issue by monzuralam** [10up/plugin-check#559]
## The plugin readme.txt does not exist.

After checking the result it says `readme.txt` doesn't exist, but I have readme.txt on my plugin directory.

**Plugin Check Result:**

![Plugin Checking result](https://github.com/user-attachments/assets/41076541-06f7-4c3e-bd01-f7579769fe20)

**Readme.txt on the plugin editor:**
![Readme.txt](https://github.com/user-attachments/assets/47719c3e-de99-495f-a946-9573c5261396)

**Comment by ernilambar** [comment]
@monzuralam Which Plugin Check version are you using? From the directory or from here GitHub?

**Comment by monzuralam** [comment]
1.0.1( WordPress Plugin Directory )
@ernilambar

**Comment by ernilambar** [comment]
> 1.0.1( WordPress Plugin Directory ) @ernilambar

Please try with latest version.

**Comment by monzuralam** [comment]
Okay. @ernilambar Thanks.
