### ISSUE TITLE
Issues in check results message CLI 

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#574]
Issue 1:

We have replaced `<br>` with `\n`. This seems to give problem in some terminal.

![Screenshot 2024-08-16 at 12 49 37 PM](https://github.com/user-attachments/assets/df6a682a-0c48-40ac-a2f9-541fd08dbb17)

Issue 2:

`wp_strip_all_tags()` seems to remove those characters in the message which we actually want to show to the user.

Actual message:

```
Short PHP opening tag used with echo; expected "<?php echo $title ..." but found "<?= $title ..." 
```

Displayed message:

```
Short PHP opening tag used with echo; expected "
```

**Comment by swissspidy** [comment]
> Issue 1:

Hmm I thought multi-line output would work, I didn't see this in my testing.

I suppose we can just replace the newlines with spaces.

> Issue 2:

Not the smartest function it seems 😅  Let's just remove it?

**Comment by ernilambar** [comment]
> > Issue 1:
> 
> Hmm I thought multi-line output would work, I didn't see this in my testing.
> 
> I suppose we can just replace the newlines with spaces.

Yah, it should work.
> 
> > Issue 2:
> 
> Not the smartest function it seems 😅 Let's just remove it?

Yah we can remove but we need to somehow remove strong tag which we are directly adding in messages like `<strong>Incorrect Stable Tag.</strong>`

**Comment by swissspidy** [comment]
We can do a simple `str_replace(array('<strong>', '</strong>'), array('', ''), $str);` for those
