### ISSUE TITLE
PODS Templates

### ISSUE THREAD

**Issue by gcgucken** [10up/plugin-check#577]
Need help with PODS plugin

**Comment by gcgucken** [comment]
Here is the issue:
The PODS WP plugin was used to create about 300 posts that show on the live site. These posts are called Plaques and e-Plaques. Here is an example from the live site, https://berkeleyplaques.org/plaque/turner-building/. As can be seen, a lot of information is included in these posts and there is much CSS styling. The live site was created some 10+ years ago using the Avada theme.

I moved the live site to staging and installed the latest Avada theme and plugins. Now the Plaques and e-Plaques posts created by PODS are not showing all the information and styling included in the originally created post. Here is an example, https://staging.berkeleyplaques.org/plaque/turner-building/

The PHP template and CSS files from the live site that are used to correctly display the posts are in the Avada staging directory. (Avada currently uses compiled style sheets.) How do I get the updated version of Avada in the staging server to "run" the single-e_plaque.php and single-plaque.php (template) files and related style.css, when a "Plaque" post permalink is clicked?

Thank you

**Comment by swissspidy** [comment]
Hi there

This repository is where development happens for the Plugin Check plugin. It has no relation to Pods and is not a place for support with any other plugins like that.

Please ask in the support forums for help with troubleshooting your site. https://wordpress.org/support/forums/

**Comment by gcgucken** [comment]
OK will do.
