### ISSUE TITLE
Include `composer.json` in release package zip

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#579]
Currently `composer.json` is not included in the release package as we have ignored it. 
In plugin review it is recommended to keep `composer.json` when **vendor** folder is kept in the plugin.

**Comment by swissspidy** [comment]
Where is that recommendation?

We should actually consider prefixing all dependencies and have them in another folder, to avoid conflicts.

**Comment by mukeshpanchal27** [comment]
> Where is that recommendation?

Could you please answer ☝️ 

[Yoast SEO](https://plugins.trac.wordpress.org/browser/wordpress-seo/tags/23.3) is also not included the `composer.json` file even they include vendor folder.

**Comment by ernilambar** [comment]
Ref : https://developer.wordpress.org/plugins/wordpress-org/common-issues/#included-unneeded-folders
