### ISSUE TITLE
Create Force_Single_Plugin_Preparation

### ISSUE THREAD

**Issue by jjgrainger** [10up/plugin-check#58]
## Description
Create a new `Force_Single_Plugin_Preparation` that will force the plugin to be checks as the only active plugin.

## Acceptance Criteria
- Class `Force_Single_Plugin_Preparation` should be created and exists at `includes/Checker/Preparations`
- Class `Force_Single_Plugin_Preparation` should extend `Preparation` interface
- Class should have a protected property `$plugin_basename`
- Class constructor accepts a single `string $plugin_basename` parameter
- Class contains a `prepare()` method that does the following
    - Check the plugin folder exists in the plugins directory using the `$plugin_basename` property
    - If the plugin does not exist, and exception is thrown
    - Ensures the plugin and the plugin check plugin are the only in the active list of plugins using the following filters:
        - `option_active_plugins`
        - `default_option_active_plugins`
    - Returns a cleanup function that removes the filters added
 - Class contains a public `filter_active_plugins()` method that accepts an `$active_plugins` parameter
    - The method checks if the `$this->plugin_basename` exists in the array, and if it does, ensures the `$plugin_basename` and plugin checker plugin name are only in the active plugins array.

## Test Coverage
- Test the `prepare` method throws and exception if the plugin does not exist in the filesystem.
- Test the `prepare` method prepares the environment by ensuring that the `get_option( 'active_plugins' )` array includes the `$plugin_basename`.
- Test the `filter_active_plugins` returns the `$plugin_basename` property and plugin checker basename in the array passed when it exist.
- Test the `prepare` method returns a callable cleanup function.

**Comment by jjgrainger** [comment]
@felixarntz new issue and AC's added for the `Force_Single_Plugin_Preparation`

**Comment by felixarntz** [comment]
@jjgrainger ACs look good, just one critical thing needs to be updated/clarified: The filter for the active plugins option should not append the plugin - we had decided to only do runtime checks when the plugin is active, so if that isn't already the case, we must not force it. The purpose of this preparation is instead to ensure _only_ that plugin is active.

Essentially, if the plugin to check is in the list of the active plugins, ensure that _only_ that plugin and the plugin check plugin itself remain in the list of active plugins after the filter.

**Comment by jjgrainger** [comment]
Thanks @felixarntz I've updated based on your comments.

**Comment by felixarntz** [comment]
Thanks @jjgrainger, ACs LGTM!

**Comment by vishalkakadiya** [comment]
@felixarntz @jjgrainger [PR](https://github.com/10up/plugin-check/pull/68) for this epic is ready for review now. Thank you!
