### ISSUE TITLE
Create With_Shared_Preperations interface

### ISSUE THREAD

**Issue by jjgrainger** [10up/plugin-check#59]
## Description
Create a `With_Shared_Preparations` interface. This interface is used on Checks that require reusable preperations.

## Acceptance Criteria
- A new `With_Shared_Preparations` interface exists in `includes/Checker/With_Shared_Preparations.php`
- The `With_Shared_Preparations` interface contains a single public `get_shared_preparations()` method
- The `get_shared_preparations()` method accepts no parameters
- The `get_shared_preparations()` method returns an array

**Comment by jjgrainger** [comment]
@felixarntz new AC's for the `With_Shared_Preperations` interface

**Comment by felixarntz** [comment]
@jjgrainger ACs LGTM. There was a type in the interface name (should be `*_Preparations`), but I quickly fixed that so this is good to proceed.

**Comment by vishalkakadiya** [comment]
@jjgrainger @felixarntz The PR https://github.com/10up/plugin-check/pull/65 is ready for review now. Thank you!
