### ISSUE TITLE
Warning about `Requires Plugins` plugin header 

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#591]
According to doc of `Requires Plugins`:

```
This must contain a comma-separated list of WordPress.org-formatted slugs for its dependencies.
```

We could warn if value of `Requires Plugins` is not as per the requirement.

Reference - https://make.wordpress.org/core/2024/03/05/introducing-plugin-dependencies-in-wordpress-6-5/

**Comment by dd32** [comment]
For context; I've helped plugin authors and it's usually one of two things:
 1. They've got it set to a non-wordpress.org-hosted item. ie. `Requires Plugins: pro-plugin-slug`
 2. They've not used a slug, ie. `Requires Plugins: Example Plugin, OtherPlugin`

**Comment by swissspidy** [comment]
(1) could be solved in a wp.org specific add-on perhaps

(2) could be some regex maybe?

**Comment by dd32** [comment]
WordPress.org rejects plugins which have an invalid dependency header, so it's not a problem for us.

It's only a problem in that plugin authors have no way of knowing currently through plugin check when they've specified an invalid header.

**Comment by ernilambar** [comment]
Will this regex be good?

```
^[a-z0-9-]+(?:,[a-z0-9-]+)*$
```
