### ISSUE TITLE
Create Runtime_Check and Static_Check interfaces

### ISSUE THREAD

**Issue by jjgrainger** [10up/plugin-check#60]
## Description
Create 2 new interfaces:
- `Runtime_Check` interface.
- `Static_Check` interface.
 
These interfaces are used by Runner classes to determine the type of Check is being run.

## Acceptance Criteria
- A `Runtime_Check` interface class exists in `includes/Checker/Runtime_Check.php`.
- The `Runtime_Check` extends the `Check` interface.
- The `Runtime_Check` interface has no methods.
- The `Abstract_Runtime_Check` class implements the `Runtime_Check` interface.
- A `Static_Check` interface class exists in `includes/Checker/Static_Check.php`.
- The `Static_Check` extends the `Check` interface.
- The `Static_Check` interface has no methods.
-  The `Abstract_PHP_CodeSniffer_Check` class implements the `Static_Check` interface.

Additionally update the following classes:
- `Abstract_Runtime_Check` implements the `Runtime_Check` interface (remove the `Check` interface)
- `Abstract_PHP_CodeSniffer_Check ` implements the `Static_Check` interface (remove the `Check` interface)

**Comment by jjgrainger** [comment]
@felixarntz AC's for the new Check interfaces have been created.

**Comment by felixarntz** [comment]
@jjgrainger A small bit of feedback on the ACs:
* Can we make `Runtime_Check` and `Static_Check` each extend `Check`?
* Based on that, we should then also change `Abstract_Runtime_Check` and `Abstract_PHP_CodeSniffer_Check` to _only_ implement the new respective interface, no longer `Check` (since that is implied as the new interfaces would extend that interface anyway).

**Comment by jjgrainger** [comment]
Thanks @felixarntz I've made the updates to the AC's based on your feedback

**Comment by felixarntz** [comment]
Thanks @jjgrainger, ACs LGTM!

**Comment by vishalkakadiya** [comment]
@jjgrainger @felixarntz The PR https://github.com/10up/plugin-check/pull/66 is ready for review now. Thank you!
