### ISSUE TITLE
Check for Plugin Header fields validation

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#600]
Introduce check for plugin header fields

* **Plugin Name** 
  - Should not be `Plugin Name` or `My Basics Plugin`
* **Plugin URI**
  - Valid URL
  - WordPress.org URL not allowed
  - Should not be example domain `example.com`
* **Description**
  - Should not contain - `This is a short description of what the plugin does`
  - Should not contain - `Here is a short description of the plugin`
  - Should not contain - `Handle the basics with this plugin`
* **Author URI**
  - Valid URL
* **Requires at least**
  - Similar to validation done in readme
* **Requires PHP**
  - Similar to validation done in readme

This way we could also incorporate https://github.com/WordPress/plugin-check/issues/591 in this same check.

Ref: https://developer.wordpress.org/plugins/plugin-basics/header-requirements/

**Comment by davidperezgar** [comment]
Good issue to prevent errors in Plugin Header!
