### ISSUE TITLE
Show a preview, like in the plugin page

### ISSUE THREAD

**Issue by javiercasares** [10up/plugin-check#614]
Parse the readme and headers of the plugin and show in the plugin check results how it should show on the WordPress.org page and the Website (user) plugin list, and maybe how it may show when replacing the plugin via ZIP upload.

With that, you may see how the user will perceive the WordPress version, PHP versions, Tested up to, tags, etc...

**Comment by davidperezgar** [comment]
That's interesting. You mean when we are making the check, right?

**Comment by javiercasares** [comment]
Yes, you do the check, and it shows "how it's ging to be".

For example, a lot of times I can see that when replacing a plugin, there is no WP or PHP versions, or something like that, so you can recommend how to include the headers to see that.

**Comment by swissspidy** [comment]
Just use something like https://wpreadme.com/?
