### ISSUE TITLE
Warn if name declared in readme file is different from plugin header

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#623]
**WARNING: Plugin name declared in readme file and plugin headers are different.**

Example:

**XYZ Tool - Nice Addon** # readme.txt
**XYZ Tool** # xyz-tool.php

**Comment by swissspidy** [comment]
Is that not allowed? Many many plugins do that

**Comment by ernilambar** [comment]
Yes, allowed. Not a required issue. That is why it should be only a warning. It is recommended to keep same in both places.
