### ISSUE TITLE
Check: Badly named files (spaces etc)

### ISSUE THREAD

**Issue by davidperezgar** [10up/plugin-check#628]
This check is based in this sentence that we use reviewing plugins:

> ## There are poorly named files in your plugin
> 
> Due to the different types of servers people use for WordPress, we do not permit the use of spaces or certain characters in file names, as they would cause conflicts. Related to this, we do not permit filenames with the same names, but using uppercase (or lowercase) to differentiate them, as they are not universally supported.

We have to make a check to see this problem.

**Comment by cyrus978** [comment]
Hi,
With the latest update, I am getting errors bad file name for **payfast.png** or **assets/js/frontend/blocks.asset.php** or
**assets/js/frontend/blocks.js**
I don't understand why these are bad file names. There is no real error message as to why this is a bad file name, just **Badly named files are not permitted.** 

assets/js/frontend/blocks.asset.php and assets/js/frontend/blocks.js are generated filenames. 

Can you point me in the right direction? Thank you.

**Comment by ernilambar** [comment]
@cyrus978 Please provide us the plugin zip (directly downloadable, Dropbox link or something) so that we can have a look.

**Comment by ernilambar** [comment]
@cyrus978 Also please check that zipped plugin file name is "plugin-slug.zip" and when it is extracted, folder name is "plugin-slug". Most probably this should solve the issue.

**Comment by Andrew-Starr** [comment]
I noticed this too with version 1.2.0

This is happening with all plugins that I checked, even plugins such as Akismet are showing this warning for every file in the plugin, including files such as the main plugin file e.g. `akismet.php,` `readme.txt`, `changelog.txt` etc and these files are obviously not badly named.

Not sure why as none of the warning file names contain any of the conflict characters that are checked for.

**Comment by Andrew-Starr** [comment]
Ahhh the issue is not with the conflict chars, but this line: `if ( preg_match( '/\s/', $file ) )`

What is this checking for?

**Comment by ernilambar** [comment]
> Ahhh the issue is not with the conflict chars, but this line: `if ( preg_match( '/\s/', $file ) )`
> 
> What is this checking for?

It was to detect space in files/folder name I believe.

**Comment by Andrew-Starr** [comment]
> It was to detect space in files/folder name I believe.

It seems to be false matching every file name.
Commenting out that code and in the Akismet example, it only warns about the `akismet-refresh-logo@2x.png` file which is a badly named file.

**Comment by ernilambar** [comment]
> > It was to detect space in files/folder name I believe.
> 
> It seems to be false matching every file name. Commenting out that code and in the Akismet example, it only warns about the `akismet-refresh-logo@2x.png` file which is a badly named file.

Are you on Windows OS?

**Comment by Andrew-Starr** [comment]
> Are you on Windows OS?

Yes.

**Comment by ernilambar** [comment]
May be full path for plugin files in your system contains space like "Program Files" or similar. Can you please check?

**Comment by cyrus978** [comment]
"May be full path for plugin files in your system contains space like "Program Files" or similar. Can you please check?"

I get the same issue. Every file for every plugin gives the "badly named" error. **Folder** names **above** the plugin directory are outside of plugin developer's control. Any one can download the plugin and extract it on windows under a folder with space( like c:\"my sites\site1" and plugin check will give a "badly named" error for every file.

**Comment by Andrew-Starr** [comment]
> May be full path for plugin files in your system contains space like "Program Files" or similar. Can you please check?

Yes that's the issue, thanks for pointing me in the right direction.

Like @cyrus978 says, it shouldn't really be necessary to check the full path above the plugin directory, or even above the WordPress installation directory.

**Comment by ernilambar** [comment]
Can you please check with the PR https://github.com/WordPress/plugin-check/pull/714 ?

**Comment by Andrew-Starr** [comment]
@ernilambar Yes I can confirm that fixes the issue.

**Comment by cyrus978** [comment]
Same here. No badly named error with the fix.
Thank you for the very quick response!

**Comment by wayheming** [comment]
I have the same problems.

**Comment by itsdavidmorgan** [comment]
I can confirm this same issue is occurring for me.

**Comment by davidperezgar** [comment]
It wasn't launched the version in the repo. That's why.
