### ISSUE TITLE
Make available the i18 checks for Plugin Repo

### ISSUE THREAD

**Issue by davidperezgar** [10up/plugin-check#632]
As we says while reviewing a plugin and we see the issue:
 
> Please do not use variable names for the text domain portion of a gettext function.  
> 
> For example, this is a bad shortcut: __( ‘Translate me.’ , $text_domain );
> 
> The text domain also needs to be added to the plugin header. WordPress uses it to internationalize your plugin meta-data even when the plugin is disabled. The text domain should be same as the one used when loading the text domain.
> 
> If your plugin permalink is wp-penfold-macrame, then your text domain should be the same.
> 
> You can read https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains for more information.

We do not allow to use variables, constants or empty values while using translation functions.

I believe that we could use i18n Sniff from WordPress Coding Standards.

**Comment by ernilambar** [comment]
Isn't this already implemented?

**Comment by davidperezgar** [comment]
No, I've tested and it not showed results

**Comment by akirk** [comment]
I have tested this with the latest trunk version and the error is reported via https://github.com/WordPress/plugin-check/blob/trunk/includes/Checker/Checks/General/I18n_Usage_Check.php:

![Screenshot 2024-09-17 at 12 49 32](https://github.com/user-attachments/assets/14e50644-4f92-4e7c-a4a4-6248a64904ef)

**Comment by davidperezgar** [comment]
Ok thanks. I see the problem. It's not in the `Plugin repo` category as well. So we have to update to review that item in Plugin repo. I'm going to change the PR.
