### ISSUE TITLE
New parameter in CLI to specify the correct slug

### ISSUE THREAD

**Issue by davidperezgar** [10up/plugin-check#644]
As @dd32 said in [#441 comment](https://github.com/WordPress/plugin-check/issues/441#issuecomment-2357911990), we need to specify the correct slug in the wp cli command, so we could compare with the ones that we have in the plugin.

It's related with PR #441

**Comment by swissspidy** [comment]
Makes sense.

This should only work when specifying a ZIP file or URL, not when trying to check an existing plugin on the site.

**Comment by davidperezgar** [comment]
I think it could be in any case.

**Comment by dd32** [comment]
> This should only work when specifying a ZIP file or URL, not when trying to check an existing plugin on the site.

I disagree, the folder something is installed in isn't necessarily the slug.  WordPress installs it into the slug folder by default, but a git checkout might exist in `my-plugin.git` or `my-plugin-trunk` alongside the currently released version.

The slug should really be sourced from the API when the explicit slug is not provided:
```
$plugin_basename = 'plugin-check/plugin.php';
$transient       = get_site_transient( 'update_plugins' );
$plugin_slug     = $transient->response[ $plugin_basename ]->slug ?? ( $transient->no_update[ $plugin_basename ]->slug ?? basename( $plugin_basename ) );
```

**Comment by davidperezgar** [comment]
Ok @dd32, @ernilambar is working on the PR #650 .
