### ISSUE TITLE
 EnqueuedScriptsScope: possible false negative?

### ISSUE THREAD

**Issue by alanef** [10up/plugin-check#648]
EnqueuedScriptsScope: frontend/js/frontend.js#L1
This script is being loaded in all contexts.

seems to examine from front end, but script that is to be applied to all front end is limited by scope  but warned
`public function enqueue_scripts() {
		if ( ! is_admin() ) {
			wp_enqueue_script( 'my-script', plugin_dir_url( __FILE__ ) . 'js/frontend.js', array(), $this->version, true );
		}
	}`

**Comment by swissspidy** [comment]
Not sure I follow. The check is supposed to warn if you are loading a script on every single frontend page, and in your code snippet that's exactly what you are doing. So what's the issue?

**Comment by alanef** [comment]
OK then it is just the wording that needs clarifucation.

"This script is being loaded in all contexts."

shoud be

"This script is being loaded in all  frontend contexts."
