### ISSUE TITLE
Check: Check the readme plugin name has the correct convention

### ISSUE THREAD

**Issue by davidperezgar** [10up/plugin-check#653]
It the Plugin name in the readme header has different syntax, it should give you an error. 

For example: 
`== Plugin Name ==`

It should give you an error as it has incorrect syntax. It needs `===` in both sides of the plugin name.

**Comment by swissspidy** [comment]
Isn't the readme parser already handling this kinda stuff? From what I can see it's pretty forgiving and doesn't actually care if for example the `===` on the right side is missing. See https://github.com/afragen/wordpress-plugin-readme-parser/blob/c3758599348148be684b3c4ad1105d09b6230d51/class-parser.php#L239-L269

**Comment by davidperezgar** [comment]
Yes, I use the validator and it works fine. But Should not warn that as a good practice?

**Comment by swissspidy** [comment]
If you think the parser should trigger a warning for this, I recommend creating a Meta Trac ticket to update the parser.

**Comment by davidperezgar** [comment]
Ok. I've made an issue in the parser. Let's close this issue.
