### ISSUE TITLE
Strange behaviour checking the plugin Lite Speed Cache 

### ISSUE THREAD

**Issue by davidperezgar** [10up/plugin-check#654]
As the developer says: 

> Hello
> I am one of the developer working at LiteSpeed Cache plugin
> When we scan our plugin in any other category than Security the results are showing.
> 
> When scanning Security category it passes late_escaping tests and it freezes at direct_db_queries for a few seconds, then it redirects to wp-admin/$url (this is the link).
> 
> Forgot to mention, I disabled LSC just to make sure there are no compatibility issues
> 
> I’ve been debugging a little bit but it seems there is a code(from our plugin) that creates a redirect while running checks.

Forum URL: https://wordpress.org/support/topic/lsc-cache/

I've tested and I get the a redirection in admin and in wpcli works correctly.

**Comment by swissspidy** [comment]
Well if their plugin is causing a redirect then that sounds more like an issue with their plugin, not with PCP 🤔

**Comment by davidperezgar** [comment]
Yes, but should we prevent that?

**Comment by swissspidy** [comment]
Plugins can do anything in WP, we can‘t detect every such misbehavior. Ideally they first try to fix their plugin

**Comment by davidperezgar** [comment]
Ok then.

**Comment by timotei-litespeed** [comment]
Hello @davidperezgar and @swissspidy 
Thank you for looking over the issue. I am the developer that noticed the redirect error on Wordpress.org

The take away is: for us to look over the issue in our polugin and try to find a fix. Yes?

Tim

**Comment by swissspidy** [comment]
Yes
