### ISSUE TITLE
Check: Not using wp_enqueue commands

### ISSUE THREAD

**Issue by davidperezgar** [10up/plugin-check#662]
Detect the use of not using enqueue functions for styles or scripts.

As we say:

> Your plugin is not correctly including JS and/or CSS. You should be using the built in functions for this:
> 
> When including JavaScript code you can use: 
> wp_register_script() and [wp_enqueue_script()](https://developer.wordpress.org/reference/functions/wp_enqueue_script/) to add JavaScript code from a file.
> [wp_add_inline_script()](https://developer.wordpress.org/reference/functions/wp_add_inline_script/) to add inline JavaScript code to previous declared scripts.
>  When including CSS you can use: 
> wp_register_style() and [wp_enqueue_style()](https://developer.wordpress.org/reference/functions/wp_enqueue_style/) to add CSS from a file.
> [wp_add_inline_style()](https://developer.wordpress.org/reference/functions/wp_add_inline_style/) to add inline CSS to previously declared CSS.
> Note that as of WordPress 6.3, you can easily pass attributes like defer or async: https://make.wordpress.org/core/2023/07/14/registering-scripts-with-async-and-defer-attributes-in-wordpress-6-3/ 
>  
> Also, as of WordPress 5.7, you can pass other attributes by using this functions and filters: https://make.wordpress.org/core/2021/02/23/introducing-script-attributes-related-functions-in-wordpress-5-7/
> If you're trying to enqueue on the admin pages you'll want to use the admin enqueues 
> 
> https://developer.wordpress.org/reference/hooks/admin_enqueue_scripts/
> https://developer.wordpress.org/reference/hooks/admin_print_scripts/
> https://developer.wordpress.org/reference/hooks/admin_print_styles/

I believe that EnqueuedResources in WPCS will solve this.

**Comment by swissspidy** [comment]
That's what our existing `Enqueued_Resources_Check` check does which uses the `WordPress.WP.EnqueuedResources` sniff.

**Comment by davidperezgar** [comment]
So, it seems that is not yin the repo, so. Let's add that category then.
