### ISSUE TITLE
Disabling Generic.PHP.DisallowShortOpenTag.EchoFound

### ISSUE THREAD

**Issue by justinkruit** [10up/plugin-check#663]
Hi, me again.

I know it's not ideal for the test, but I personally prefer the short php echo way `<?=`, but this gets flagged by `Generic.PHP.DisallowShortOpenTag.EchoFound`. Is there a way to disable this test?

**Comment by ernilambar** [comment]
That must be coming from `plugin_review_phpcs` check. Plugin Check does not have feature to exclude individual error code yet.

**Comment by swissspidy** [comment]
@mukeshpanchal27 Do you recall why this specific sniff was added in #187? Do the plugin directory guidelines disallow short opening tags?

**Comment by mukeshpanchal27** [comment]
At the time of new PCP release, we incorporate the old PCP checks and this sniff is part of the old implementation see https://plugins.trac.wordpress.org/browser/plugin-check/tags/0.2.3/checks/phpcs/plugin-check.xml#L59 so we incorporate the changes to new one so it will not missed.

Till then i don't think anyone updates it.

**Comment by davidperezgar** [comment]
We don't allow php short tags in directory. You can see it here:
https://developer.wordpress.org/plugins/wordpress-org/common-issues/#php-changing-settings-globally

**Comment by justinkruit** [comment]
But the short hand echo isn't a php setting. Since php 5.3 it is always enabled and doesn't listen to the disabling shorthand setting from PHP.

**Comment by swissspidy** [comment]
That's what the link above also says. It also says that short open tags are not allowed in the directory.

Given that they are not allowed in the directory, I am closing this as a wontfix.
