### ISSUE TITLE
Convert `plugin_header_invalid_requires_wp` and `plugin_header_invalid_requires_php` codes to error

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#673]
Following codes should be blocker instead of warning. If values are not sane those will affect the WP core's update procedure.

* plugin_header_invalid_requires_wp
* plugin_header_invalid_requires_php

**Comment by sybrew** [comment]
This is against the Open Source ethos. 

Headers do not affect WP Core update procedures unless WP Core listens to them. 

Those that aren't affecting WP Core directly should be removed.
