### ISSUE TITLE
Allow `Abstract_PHP_CodeSniffer_Check` based check to add `runtime-set` arguments

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#679]
Currently only following args are allowed:

* standard
* extensions
* sniffs
* exclude

**Use case:**

What I am trying to do is running PHPCS with `--runtime-set text_domain plugin-slug`. As of now, this does not seem to be possible.

**Comment by davidperezgar** [comment]
Yes, that's needed for language check in Plugin submission.
