### ISSUE TITLE
CLI: if "wp plugin check <my-plugin>" finds no errors/warnings, then output a message saying such

### ISSUE THREAD

**Issue by pbiron** [10up/plugin-check#685]
thanx for this useful plugin.  I've used it several times from the WP Dashboard (`Tools > Plugin Check`).  Today I tried the WP_CLI `wp plugin check` command for the first time.

It would be helpful if the `check` command output a `WP_CLI::success()` message if no errors/warnings are found.  The way things are it is not possible to know whether there were no errors/warnings or whether there was a run-time fatal while the `check` command was running (without consulting the PHP error log).

Not sure how such a message might affect the GitHub Action, as I don't use GH actions ;-)

If there is consensus that this would be a good idea, I'm happy to do a PR.

**Comment by davidperezgar** [comment]
Ok! I agree to say that there is no problem.

**Comment by pbiron** [comment]
I'll do a PR tomorrow
