### ISSUE TITLE
Show errors with severity less than a number as a warning

### ISSUE THREAD

**Issue by davidperezgar** [10up/plugin-check#691]
In WP-CLI, when we use severity, such as 7 for errors, we lose the results of those errors and they are not displayed. My proposal would be to show them as warnings, so the user can still address them since they are important, but they do not block the process.

The severity level 7 is used in the [WordPress Plugin Submission](https://meta.trac.wordpress.org/changeset/14074), and it filters errors with a severity level lower than 7. That's correct, but we are losing other issues that, if the user received those results, they could work on them. However, it wouldn't block the submission. Therefore, we could display them as warnings.

**Comment by davidperezgar** [comment]
What do you think @felixarntz, @swissspidy @ernilambar @barrykooij ?

**Comment by frantorres** [comment]
It makes sense to display issues bellow the level of error as warnings (or "not blocking errors" to be more accurate and avoid confusion between what's an error and what's a warning).

I understand that this is related to the "filter" applied to the wp-cli command, so maybe will need a new parameter to say that we also want so see issues bellow 7 but not marked as an error.
