### ISSUE TITLE
can't sanitize array_keys

### ISSUE THREAD

**Issue by jcvignoli** [10up/plugin-check#697]
I want to retrieve the keys of a POST array and sanitize it. Can't find the correct way to do it.

`array_map( 'sanitize_text_field', array_keys( wp_unslash( $_POST['data'] ) ) );`

Gives `WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, Detected usage of a non-sanitized input variable: $_POST['data']`

Without the array_keys() function, this is ok though:

`array_map( 'sanitize_text_field', wp_unslash( $_POST['data'] ) );`

How can I sanitize an array_keys() ?

**Comment by dd32** [comment]
Your original code is fine, and it's just a false-positive report.

Code checkers aren't 100% accurate, and not all warnings are there to be fixed.

**Comment by jcvignoli** [comment]
Hi @dd32 

The thing is that check failure results in github action failure on my side, as I'm using WP Plugin action on github https://github.com/WordPress/plugin-check-action

I don't know how to succeed the validation...

**Comment by davidperezgar** [comment]
We will work with WPCS to prevent this kind of false positives. Right now, we cannot do anything else.

**Comment by jcvignoli** [comment]
Thanks @davidperezgar. Looking forward to a joint solution with WPCS.
