### ISSUE TITLE
Create Check Abstract Classes

### ISSUE THREAD

**Issue by mehulkaklotar** [10up/plugin-check#7]
In addition to the Check interface, there will be 2 abstract classes as part of the infrastructure that provides the foundation for the concrete check classes developed in the plugin.

- [x] https://github.com/10up/plugin-check/issues/8
- [x] https://github.com/10up/plugin-check/issues/9

### PHP_CodeSniffer_Check
This abstract class will be used to create concrete check classes that perform static analysis. This class will provide foundational methods that allow concrete classes to define code standards and sniffs to test the plugin code against. It will also contain an instance of PHP_CodeSniffer\Runner to run the tests and return the results to be processed.
### Runtime_Check
This abstract class will be used to create concrete checks that perform runtime analysis. These checks will run elements of the plugin code on the server to test its behavior against an expected outcome.

**Comment by jjgrainger** [comment]
@eclarke1 @FlicHollis I'm removing this ticket as it's an overview ticket and it's not helpful for milestone one.
