### ISSUE TITLE
Check: uninstall.php existence

### ISSUE THREAD

**Issue by threadi** [10up/plugin-check#700]
Would it also be possible to add a check whether the `uninstall.php` exists? Unfortunately, many plugins forget this routine that should clean up after them. Checking for its presence should help to draw more attention to it.

**Comment by swissspidy** [comment]
How would you expect this to work? Not every plugin adds data that needs to be cleaned up.

Also note that register_uninstall_hook exists too.

**Comment by threadi** [comment]
The hook has its disadvantages, as described here: https://developer.wordpress.org/reference/functions/register_uninstall_hook/

Both methods are described in the manual: https://developer.wordpress.org/plugins/plugin-basics/uninstall-methods/

Couldn't you check both and if neither is available, at least display a warning?

**Comment by swissspidy** [comment]
> Couldn't you check both and if neither is available, at least display a warning?

That would mean throwing a warning for almost every plugin out there, which is too noisy IMO. But I'll let others weigh in.

**Comment by ernilambar** [comment]
> > Couldn't you check both and if neither is available, at least display a warning?
> 
> That would mean throwing a warning for almost every plugin out there, which is too noisy IMO. But I'll let others weigh in.

Agree. Most of the plugins does not even need uninstall actions.
