### ISSUE TITLE
False positive "WordPress.Security.EscapeOutput.OutputNotEscaped" on echo submit_button() or get_the_title()

### ISSUE THREAD

**Issue by thenickless** [10up/plugin-check#709]
submit_button() already handles the escaping of its output internally, ensuring the content is properly sanitized before being rendered.
get_the_title() also escapes the title with esc_html() internally when called, making it safe for direct output.

Example:

The following code triggers a false positive warning:
`echo submit_button('Save Changes');`

`echo get_the_title();`

In both cases, the plugin reports a violation:
WordPress.Security.EscapeOutput.OutputNotEscaped

**Comment by swissspidy** [comment]
Hi there,

Please report enhancement suggestions or possible false positive in `WordPress.*` sniffs at https://github.com/WordPress/WordPress-Coding-Standards. Plugin Check is just a consumer of those sniffs.

**Comment by ernilambar** [comment]
Sidenote: submit_button() already prints the output. So `echo submit_button('Save Changes');` does not make sense. It should be simply `submit_button('Save Changes');`
