### ISSUE TITLE
Allow MPL 2.0 License

### ISSUE THREAD

**Issue by davidperezgar** [10up/plugin-check#719]
The MPL 2.0 is compatible with GPL, and there are few instances of MPL 2.0 also in few plugins.

More information about the license:
https://www.gnu.org/licenses/license-list.en.html#MPL-2.0

Not other versions are compatible, so we should develop only for that version.

Links:
https://www.tldrlegal.com/license/mozilla-public-license-2-0-mpl-2#:~:text=MPL%20is%20a%20copyleft%20license,GPL%20version%202%20or%20greater.

https://www.mozilla.org/en-US/MPL/2.0/FAQ/

**Comment by chriscct7** [comment]
Specifically versions below 2.0 are not compatible, so that can be version_compare'd against
