### ISSUE TITLE
Escape-output errors generated by included WordPress core classes

### ISSUE THREAD

**Issue by samglover** [10up/plugin-check#727]
I believe I'm following the [instructions for using WP_List_Table in a plugin](https://developer.wordpress.org/reference/classes/wp_list_table/#Developer_Usage), but I'm getting escape-output errors from Plugin Check for the included **class-wp-list-table.php** file. For example:

**FILE: path-to-plugin/includes/class-wp-list-table.php**
Line | Column | Type | Code | Message
-- | -- | -- | -- | --
379 | 9 | ERROR | WordPress.Security.EscapeOutput.UnsafePrintingFunction | All output should be run through an escaping function (like esc_html_e() or esc_attr_e()), found '_e'.
417 | 93 | ERROR | WordPress.Security.EscapeOutput.OutputNotEscaped | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$text'.

I have added one modification to the **class-wp-list-table.php** file in order to use it in a namespace:

`namespace Client_Power_Tools\Core\Includes;`

And I am therefore initiating the instantiating the class with:

```
use Client_Power_Tools\Core\Includes;
class Project_List_Table extends Includes\WP_List_Table  {
  …
}
```

I don't think this is the reason it is generating this error, because if I "un-namespace" the plugin I still get the error. 

Is this the intended behavior? If so, I assume it means I will have to edit **class-wp-list-table.php** extensively in order to include it in my code (there are over 100 errors for the file). I can do that; it just seems like core files, when included, would be better left alone.

If it helps, my plugin code is here: [samglover/client-power-tools](https://github.com/samglover/client-power-tools/tree/fix_plugin_check_errors).

**Comment by swissspidy** [comment]
You shouldn't need to copy whole files from core into your plugins. If you want to extend `WP_List_Table`, just load the class & extend it. No reason to copy the code.

> Is this the intended behavior?

Yes.

Simply put, there are different rules for core code and plugins. What is OK in core might not be OK in a plugin.

So if you have tons of `echo` statements in your plugins' code without proper escaping, that's a legit thing Plugin Check is telling you about that you should address.

But again, there really shouldn't be any need to 1:1 copy this file in the first place.
