### ISSUE TITLE
Convert readme check WARNINGs to ERRORs

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#728]
Check: Plugin_Readme_Check

| Error Code | Current Type (Severity) | Proposed Type (Severity) |
| --- | --- | --- |
| no_plugin_readme | WARNING (9) | ERROR (9) |
| default_readme_text | WARNING (7) | ERROR (7) |

**Comment by ernilambar** [comment]
CC @frantorres @davidperezgar

**Comment by davidperezgar** [comment]
Yes, I'm agree with these changes.

**Comment by frantorres** [comment]
Agree too, thanks!
