### ISSUE TITLE
Remove checks list from the docs/README.md

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#736]
Remove `Checks Developed in the Plugin` section from `docs/README.md`

Ref - https://github.com/WordPress/plugin-check/blob/trunk/docs/README.md

- Current list is incomplete and unmaintained.
- Severity is attached to the error code, not checks. So `Severity` column is not correct.
- Moreover this list is an extra maintenance burden with little usefulness.
- We already have `plugin list-checks` CLI command with which user can see these details.

If we really want to list checks in the markdown format, we could develop some script which will dynamically fetch checks and generate the markdown file.

**Comment by ernilambar** [comment]
CC @swissspidy @davidperezgar

**Comment by swissspidy** [comment]
Makes sense to remove that file, but we should have a list _somewhere_, i.e. the plugin readme or devhub.

**Comment by davidperezgar** [comment]
Yes, we need that list.

**Comment by davidperezgar** [comment]
I'd add in the instructions to create a new release, update this list.
