### ISSUE TITLE
Restrict `parse_str()` without second argument

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#756]
`parse_str()` without second argument is restricted.

> Using this function without the result parameter is highly DISCOURAGED and DEPRECATED as of PHP 7.2. As of PHP 8.0.0, the result parameter is mandatory.

Developing sniff using `AbstractFunctionParameterSniff` would be most feasible route I believe.

**Comment by swissspidy** [comment]
The `PHPCompatibility` project has a dedicated `PHPCompatibility.FunctionUse.OptionalToRequiredFunctionParameters` sniff that catches exactly this.

No need to reinvent the wheel.

I would suggest  adding`PHPCompatibility` as a whole to `plugin-review.xml`, as it helps plugins keep up to date with PHP compatibility

**Comment by ernilambar** [comment]
Do you mean adding `PHPCompatibility.FunctionUse.OptionalToRequiredFunctionParameters` or whole `PHPCompatibility`? I will discuss it in the team meeting accordingly.

Regarding `parse_str()` particularly, currently it is enforced in internal scanner for any PHP version. Would it be possible to customize `OptionalToRequiredFunctionParametersSniff` class?

**Comment by swissspidy** [comment]
I don‘t know, you will have to check

**Comment by chriscct7** [comment]
It seems like it'd be better to copy the one test as opposed to including the entire library since we'd have to do that as a non-stable (dev branch)
