### ISSUE TITLE
Add `PHPCompatibility` in `plugin-review.xml`

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#763]
From https://github.com/WordPress/plugin-check/issues/756#issuecomment-2441370401

> I would suggest adding `PHPCompatibility` as a whole to `plugin-review.xml`, as it helps plugins keep up to date with PHP compatibility.

**Comment by ernilambar** [comment]
Closing as `maybelater`. 
We should definitely add this when version `10.0.0` of PHPCompatibility is released. Hopefully soon.

**Comment by davidperezgar** [comment]
ok!
