### ISSUE TITLE
Warning when the plugin name in the readme.txt file differs from the plugin header (bug with translations)

### ISSUE THREAD

**Issue by Rod-Gomes** [10up/plugin-check#764]
My plugin is receiving a "mismatched_plugin_name" warning when the plugin name is translated.

The plugin name is consistent in both the readme.txt file and the plugin header. However, when using a translated version of the plugin in a language other than English, this warning starts to appear.

**Comment by davidperezgar** [comment]
Hello, 
Yes, I see the problem 
 ![Image](https://github.com/user-attachments/assets/eb2f1e76-e71b-4b7c-9259-3fc98f15b54c)

And I can find a solution for that.

**Comment by ernilambar** [comment]
We should add test also. May be Behat test is suitable for this issue I guess.
