### ISSUE TITLE
Using WordPress translations for i18n calls

### ISSUE THREAD

**Issue by joho1968** [10up/plugin-check#795]
What is the correct way to utilize already translated strings in the WordPress core?

Using `'default'` as the text domain does not seem to work as it generates a warning to the effect of:

`Mismatched text domain. Expected 'slug_for_my_plugin' but got 'default'. `

(`WordPress.WP.I18n.TextDomainMismatch`)

Or am I expected to duplicate the translation of the strings in my own plugin? 🤔

**Comment by ernilambar** [comment]
Using `default` textdomain is not recommended but allowed. This has been fixed in the plugin repo. It will be released in new version `1.3` in few days.

**Comment by swissspidy** [comment]
> What is the correct way to utilize already translated strings in the WordPress core?

You don‘t :-) Unless you really know what you‘re doing. Which is why it‘s only a warning, not an error

> Or am I expected to duplicate the translation of the strings in my own plugin?

Ideally yes, this is best for tramslators.
