### ISSUE TITLE
Make error code `plugin_header_invalid_requires_plugins` an ERROR with severity 7

### ISSUE THREAD

**Issue by ernilambar** [10up/plugin-check#806]
In the directory when `Requires Plugins` value is invalid, even new release of plugin is blocked. Its value should be comma separated plugin slug and those plugins should exist in the directory.

May be it is not feasible to check existence of the plugin in the PCP, we could at least raise an ERROR if the value is not proper comma separated slugs.

Error:

```
Requires Plugins: WooCommerce
```

Expected:
```
Requires Plugins: woocommerce
```

**Comment by davidperezgar** [comment]
Ok. I see then.
