### ISSUE TITLE
Plugin checker architectural code review

### ISSUE THREAD

**Issue by eclarke1** [10up/plugin-check#82]
As part of the Milestone 1 Review a code review of the entire codebase should be done to determine any (potentially breaking) changes that should be made to the architecture before continuing with the rest of the [Checks outline in Milestone 2](https://github.com/orgs/10up/projects/12/views/1?filterQuery=label%3A%22Milestone+2%22).

This should be an holistic code review covering many aspects. Below is a partial list of what the code review should cover.

- Ensure all docblock comments are correct and up to date.
- Ensure translation strings are used correctly throughout.
- All input is validated and sanitized, all output is escaped correctly.
- Review the overall file/folder structure and if there are any improvements that can be made.
- If any classes/methods that can be renamed to make the API easier to understand.
- Identifying any bugs within the codebase.
- If there are any opportunities for additional hooks that can be added for extending the plugin checker functionality.
- Looking for any parts of the codebase that are repeated or could be refactored.
- Looking for ways to refactor the code base to make elements of the infrastructure simpler.
- Identifying parts of the codebase that are too tightly coupled between different subsystems and could be decoupled by small refactoring.
- Ensure unit tests cover important parts of the codebase.

**Comment by jjgrainger** [comment]
Hi @felixarntz I've updated the issue description with a bullet list of items to look out for during the architectural review. This is an incomplete list so feel free to add/feedback on anything you think is missing. Thanks.

**Comment by felixarntz** [comment]
Thanks @jjgrainger, looks good! I added one extra point for something to also look out for (the 2nd to last one).

**Comment by jjgrainger** [comment]
Thanks @felixarntz moving this to todo

**Comment by felixarntz** [comment]
Closing this since it was completed a while ago.
