### ISSUE TITLE
Run Runner Cleanup functions

### ISSUE THREAD

**Issue by jjgrainger** [10up/plugin-check#85]
The CL/AJAX runners that are initialized in the `Plugin_Request_Utility` have a prepare method that returns a cleanup function that needs to be run at the end of the process.

[See this comment for details](https://github.com/10up/plugin-check/pull/80/files#r1110168672).

## Acceptance Criteria
- Create a static `destroy_runner` method for the `Plugin_Request_Utility`.
-  This method will run cleanup function returned by the runners `prepare()` method and stored in the `static::$cleanup` variable.
- After calling the cleanup function, the `Plugin_Request_Utility::$runner` variable is set to `null`

**Comment by felixarntz** [comment]
@jjgrainger I think for now it's probably best to go with option 1, as that avoids side effect. Maybe we should call this method `cleanup_runner` or `destroy_runner()`?

Eventually, the AJAX route that also runs the individual check (via the concrete runner) will be able to call this static method afterwards, before returning a response. For CLI, it would probably be the WP-CLI command itself that would call the static method after running all checks, before terminating.

**Comment by jjgrainger** [comment]
Thanks @felixarntz I've updated the AC's based on your comment ready for your review.

**Comment by felixarntz** [comment]
@jjgrainger Thanks, ACs LGTM!
