### ISSUE TITLE
AJAX Runtime Environment Setup/Cleanup

### ISSUE THREAD

**Issue by jjgrainger** [10up/plugin-check#86]
This issue will implement the runtime environment setup and cleanup for AJAX requests. This will utilise the `Runtime_Environment_Setup` class to setup the WP environment before checks are run, and cleanup the environment once all checks are complete.

This issue is dependent on the following:
- #90 

### Create a Runtime Setup AJAX endpoint
- In the `Admin_Ajax` should create a new AJAX endpoint for the action `plugin_check_setup_environment`
- A new action is created for `wp_ajax_plugin_check_setup_environment` that calls a `setup_environment` method on the `Admin_Ajax` class.
- A public `has_runtime_check` method exists in the `Abstract_Check_Runner` class. This method will test the checks returned by `get_checks_to_run()`. If there is is at least 1 `Runtime_Check` it will return `true`, otherwise `false`.
- The `setup_environment` method.
    - This method will get an instance of the `AJAX_Runner` class via the `Plugin_Request_Utility::get_runner()` method.
        - If the `Plugin_Request_Utility::get_runner()` returns `null` a new instance of the `AJAX_Runner` class should be created.
    - Run the `set_check_slugs()` and `set_plugin_slug ()` methods  on the `AJAX_Runner` instance passing in the the appropriate values taken from the request. 
    - The method will test if any of the checks requested are Runtime checks by calling the `AJAX_Runner` `has_runtime_check()` method. If this returns `true` the `Runtime_Environment_Setup` class will be instantiated and it's `setup()` method called.
    - The method will then return a JSON response for the AJAX request with the following structure `{ "success": true|false, "message": (string) success/error message }`
        - An error response will be returned if setup had a critical error passing `success` as `false` and the message of the error that occured.
        - If the setup was successful, a success response will be returned with `success` as `true` and the message `"runtime environment setup successful"`
        - If the setup did not need to run, a success response will be returned with `success` as `true` and the message `"no runtime checks, runtime environment was not setup"`
- The `plugin-check-admin.js` file will be updated to first send an AJAX request to the `admin-ajax.php` endpoint with the `plugin_check_setup_environment` action before any check requests are sent.
- The request will also pass the plugin and checks to be run to the endpoint in order to determine if the runtime environment needs to be setup.
- If there is an error response, a user friendly error message will be displayed on the admin page and no further AJAX requests will be sent to attempt to run checks,

### Create a Runtime Cleanup AJAX endpoint
- In the `Admin_Ajax` should create a new AJAX endpoint for the action `plugin_check_cleanup_environment`
- A new action is created for `wp_ajax_plugin_check_cleanup_environment` that calls a `cleanup_environment` method on the `Admin_Ajax` class.
- The `cleanup_environment` method:
    - This method will test if the runtime environment had been prepared by checking if the any of the tables with the `wppc_` prefix exist.
    - If the `wppc_` tables exist, the `Runtime_Environment_Setup` class will be instantiated and it's `cleanup()` method called.
    - The method will then return a JSON response for the AJAX request with the following structure `{ "success": true|false, "message": (string) success/error message }`
        - An error response will be returned if cleanup had a critical error passing `success` as `false` and the message of the error that occured.
        - If the setup was successful, a success response will be returned with `success` as `true` and the message `"runtime environment cleanup successful"`
        - If the setup did not need to run, a success response will be returned with `success` as `true` and the message `"Runtime environment was not prepared, cleanup was not run."`
- The `plugin-check-admin.js` file will be updated to send a final AJAX request to the `admin-ajax.php` endpoint with the `plugin_check_cleanup_environment` action after all checks have been run.
- The request will also pass the plugin and checks to be run to the endpoint in order to determine if the runtime environment needs to be cleaned up.

**Comment by felixarntz** [comment]
@jjgrainger The ACs here overall look good. Just one critical related question: Which issue is responsible for implementing the AJAX action to get the list of checks to run (expose it to the client)? I'm asking because we will need this anyway to later send the individual AJAX requests (one per check), and we should preferably pass the list of checks to run to the two AJAX actions you're defining here as well, to make it more decoupled. In the future we may want to also add UI to provide more control on which checks to run, in which case this will become a necessity, but in terms of decoupling I think it's a good idea to already have the list of checks to run always be passed to the AJAX actions that in any way use checks.

And one nit-pick suggestion:
> If the setup was successful, or did not need to run, a success response will be returned.

I would suggest we still add a way to differentiate the responses for whether the runtime preparation was made or not. Both should be success responses indeed, and we probably won't need to use this differentiation in the UI, but it will be useful for debugging as well as for unit testing.

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

The issue related to the endpoint to get the checks to run has been created here https://github.com/10up/plugin-check/issues/90 based on your comment https://github.com/10up/plugin-check/issues/84#issuecomment-1442314979

I've updated the AC's here to differentiate between the success response when either the runtime environment setup is successful or not run at all.

Please review and let me know if you have any other feedback. Thanks!

**Comment by felixarntz** [comment]
@jjgrainger ACs pretty much LGTM. Just one idea for consideration: You mention in the cleanup endpoint that it also checks whether any of the checks is a runtime check. This definitely works, but I wonder whether we should instead rather check whether the environment _is_ currently "prepared", e.g. whether the `wppc_` tables exist or something like that. Arguably we want to clean up the environment if it is currently "prepared" (i.e. not clean), so maybe it would be more reliable to check for that.

Both ways should work, but they're different approaches. I'm curious what you think.

**Comment by jjgrainger** [comment]
Thanks @felixarntz I agree here that we should test if the runtime environment was prepared, rather than what checks were run as this would be more reliable in testing and cleaning up the environment.

I've updated the AC's here, please can you review. Thanks.

**Comment by felixarntz** [comment]
@jjgrainger ACs LGTM based on where we were before. However I'll leave this in the AC Review column for now as it will need to receive a small update based on the new issue we discussed just earlier in our call: Once we have a way to set the checks to run and the plugin basename in the runner classes, we should use that technique here. We also need to make sure that if no runner class was set in `object-cache.php` file, then we instantiate that here, as discussed as well.

**Comment by jjgrainger** [comment]
Thanks @felixarntz 

Based on the changes in #95 I've updated this to include creating the `AJAX_Runner` instance manually if it was not already created and use the new methods to set the check slugs and plugin slug.

Back to you for approval.

**Comment by felixarntz** [comment]
@jjgrainger One small thing regarding the ACs:
> When creating the `AJAX_Runner` instance, the `set_check_slugs()` and `set_plugin_slug ()` methods should be called passing in the appropriate values taken from the request.

These methods should be called on the instance regardless of whether the instance is created here or retrieved from `Plugin_Request_Utility`. If the latter, we should still set the correct param values just to trigger the validation added in #95 - basically to ensure everything is working as expected.

Everything else looks good to go, so no need for another review on this following the above. Of course some method names here have now changed based on #95, but that'll be clear when implementing the PR, so no need to update those in the ACs.

**Comment by jjgrainger** [comment]
Thanks @felixarntz updated and moved to todo
