### ISSUE TITLE
Add Stability flag for Plugin Check CLI command

### ISSUE THREAD

**Issue by jjgrainger** [10up/plugin-check#92]
## Description

* Add two constants `STABILITY_STABLE` and `STABILITY_EXPERIMENTAL` to the `Check` interface.
* Add a public method `get_stability()` to check `Check` interface.
* Implement traits `Stable_Check` and `Experimental_Check` that simply implement the above method and return the corresponding constant value.
* Update all existing checks to use the `Stable_Check` trait (since none of our current checks is experimental).
* Add a `INCLUDE_EXPERIMENTAL` bitwise flag to the `Check_Repository` interface. Then update `Default_Check_Repository::get_checks()` to filter out experimental checks from the list _unless_ the passed `$flags` match `INCLUDE_EXPERIMENTAL`.
- Add an optional `--include-experimental` flag to the plugin check CLI command. If set, the above infrastructure should be used to also include experimental checks.

**Comment by felixarntz** [comment]
Related: #203 

I have completed ACs here for review, based on considerations that went into the above issue.

**Comment by jjgrainger** [comment]
Thanks @felixarntz AC's look good to me, @mukeshpanchal27 do you want to review also?

**Comment by mukeshpanchal27** [comment]
Thanks @felixarntz AC's look good to me.
